package com.sinosoft.core.db.model;

public class CalMode {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cal_mode.CAL_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private Integer calId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cal_mode.CAL_CODE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String calCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cal_mode.CAL_TYPE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String calType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cal_mode.CAL_NAME
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String calName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cal_mode.CAL_SQL
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String calSql;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cal_mode.REMARK
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cal_mode.CAL_ID
	 * @return  the value of t_cal_mode.CAL_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public Integer getCalId() {
		return calId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cal_mode.CAL_ID
	 * @param calId  the value for t_cal_mode.CAL_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setCalId(Integer calId) {
		this.calId = calId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cal_mode.CAL_CODE
	 * @return  the value of t_cal_mode.CAL_CODE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getCalCode() {
		return calCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cal_mode.CAL_CODE
	 * @param calCode  the value for t_cal_mode.CAL_CODE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setCalCode(String calCode) {
		this.calCode = calCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cal_mode.CAL_TYPE
	 * @return  the value of t_cal_mode.CAL_TYPE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getCalType() {
		return calType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cal_mode.CAL_TYPE
	 * @param calType  the value for t_cal_mode.CAL_TYPE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setCalType(String calType) {
		this.calType = calType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cal_mode.CAL_NAME
	 * @return  the value of t_cal_mode.CAL_NAME
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getCalName() {
		return calName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cal_mode.CAL_NAME
	 * @param calName  the value for t_cal_mode.CAL_NAME
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setCalName(String calName) {
		this.calName = calName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cal_mode.CAL_SQL
	 * @return  the value of t_cal_mode.CAL_SQL
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getCalSql() {
		return calSql;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cal_mode.CAL_SQL
	 * @param calSql  the value for t_cal_mode.CAL_SQL
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setCalSql(String calSql) {
		this.calSql = calSql;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cal_mode.REMARK
	 * @return  the value of t_cal_mode.REMARK
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cal_mode.REMARK
	 * @param remark  the value for t_cal_mode.REMARK
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}