package com.sinosoft.core.db.model;

import java.util.Date;

public class DefCom {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.COM_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private Long comId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.COM_CODE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String comCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.COM_NAME
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String comName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.GRADE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.STATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.START_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.END_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.PROVINCE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.CITY
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.COUNTRY
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String country;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.STREET
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String street;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.ZIPCODE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String zipcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.PHONE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.FAX
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String fax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.WEBSITE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String website;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.MANAGER_NAME
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String managerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.MANAGER_MOBILE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String managerMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.PARENT_COM_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private Long parentComId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.BELONG_START_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private Date belongStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.BELONG_END_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private Date belongEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.RC_STATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private String rcState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.CREATE_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.MODIFY_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private Date modifyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.OPER_COM_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private Long operComId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.CREATE_USER_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private Long createUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_def_com.MODIFY_USER_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	private Long modifyUserId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.COM_ID
	 * @return  the value of t_def_com.COM_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public Long getComId() {
		return comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.COM_ID
	 * @param comId  the value for t_def_com.COM_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setComId(Long comId) {
		this.comId = comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.COM_CODE
	 * @return  the value of t_def_com.COM_CODE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getComCode() {
		return comCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.COM_CODE
	 * @param comCode  the value for t_def_com.COM_CODE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.COM_NAME
	 * @return  the value of t_def_com.COM_NAME
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getComName() {
		return comName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.COM_NAME
	 * @param comName  the value for t_def_com.COM_NAME
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setComName(String comName) {
		this.comName = comName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.GRADE
	 * @return  the value of t_def_com.GRADE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.GRADE
	 * @param grade  the value for t_def_com.GRADE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setGrade(String grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.STATE
	 * @return  the value of t_def_com.STATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.STATE
	 * @param state  the value for t_def_com.STATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.START_DATE
	 * @return  the value of t_def_com.START_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.START_DATE
	 * @param startDate  the value for t_def_com.START_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.END_DATE
	 * @return  the value of t_def_com.END_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.END_DATE
	 * @param endDate  the value for t_def_com.END_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.PROVINCE
	 * @return  the value of t_def_com.PROVINCE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.PROVINCE
	 * @param province  the value for t_def_com.PROVINCE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.CITY
	 * @return  the value of t_def_com.CITY
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.CITY
	 * @param city  the value for t_def_com.CITY
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.COUNTRY
	 * @return  the value of t_def_com.COUNTRY
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.COUNTRY
	 * @param country  the value for t_def_com.COUNTRY
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.STREET
	 * @return  the value of t_def_com.STREET
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getStreet() {
		return street;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.STREET
	 * @param street  the value for t_def_com.STREET
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setStreet(String street) {
		this.street = street;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.ZIPCODE
	 * @return  the value of t_def_com.ZIPCODE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getZipcode() {
		return zipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.ZIPCODE
	 * @param zipcode  the value for t_def_com.ZIPCODE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.PHONE
	 * @return  the value of t_def_com.PHONE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.PHONE
	 * @param phone  the value for t_def_com.PHONE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.FAX
	 * @return  the value of t_def_com.FAX
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.FAX
	 * @param fax  the value for t_def_com.FAX
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.WEBSITE
	 * @return  the value of t_def_com.WEBSITE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getWebsite() {
		return website;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.WEBSITE
	 * @param website  the value for t_def_com.WEBSITE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setWebsite(String website) {
		this.website = website;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.MANAGER_NAME
	 * @return  the value of t_def_com.MANAGER_NAME
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getManagerName() {
		return managerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.MANAGER_NAME
	 * @param managerName  the value for t_def_com.MANAGER_NAME
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setManagerName(String managerName) {
		this.managerName = managerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.MANAGER_MOBILE
	 * @return  the value of t_def_com.MANAGER_MOBILE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getManagerMobile() {
		return managerMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.MANAGER_MOBILE
	 * @param managerMobile  the value for t_def_com.MANAGER_MOBILE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setManagerMobile(String managerMobile) {
		this.managerMobile = managerMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.PARENT_COM_ID
	 * @return  the value of t_def_com.PARENT_COM_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public Long getParentComId() {
		return parentComId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.PARENT_COM_ID
	 * @param parentComId  the value for t_def_com.PARENT_COM_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setParentComId(Long parentComId) {
		this.parentComId = parentComId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.BELONG_START_DATE
	 * @return  the value of t_def_com.BELONG_START_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public Date getBelongStartDate() {
		return belongStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.BELONG_START_DATE
	 * @param belongStartDate  the value for t_def_com.BELONG_START_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setBelongStartDate(Date belongStartDate) {
		this.belongStartDate = belongStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.BELONG_END_DATE
	 * @return  the value of t_def_com.BELONG_END_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public Date getBelongEndDate() {
		return belongEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.BELONG_END_DATE
	 * @param belongEndDate  the value for t_def_com.BELONG_END_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setBelongEndDate(Date belongEndDate) {
		this.belongEndDate = belongEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.RC_STATE
	 * @return  the value of t_def_com.RC_STATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public String getRcState() {
		return rcState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.RC_STATE
	 * @param rcState  the value for t_def_com.RC_STATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setRcState(String rcState) {
		this.rcState = rcState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.CREATE_DATE
	 * @return  the value of t_def_com.CREATE_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.CREATE_DATE
	 * @param createDate  the value for t_def_com.CREATE_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.MODIFY_DATE
	 * @return  the value of t_def_com.MODIFY_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public Date getModifyDate() {
		return modifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.MODIFY_DATE
	 * @param modifyDate  the value for t_def_com.MODIFY_DATE
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.OPER_COM_ID
	 * @return  the value of t_def_com.OPER_COM_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public Long getOperComId() {
		return operComId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.OPER_COM_ID
	 * @param operComId  the value for t_def_com.OPER_COM_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setOperComId(Long operComId) {
		this.operComId = operComId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.CREATE_USER_ID
	 * @return  the value of t_def_com.CREATE_USER_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public Long getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.CREATE_USER_ID
	 * @param createUserId  the value for t_def_com.CREATE_USER_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setCreateUserId(Long createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_def_com.MODIFY_USER_ID
	 * @return  the value of t_def_com.MODIFY_USER_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public Long getModifyUserId() {
		return modifyUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_def_com.MODIFY_USER_ID
	 * @param modifyUserId  the value for t_def_com.MODIFY_USER_ID
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	public void setModifyUserId(Long modifyUserId) {
		this.modifyUserId = modifyUserId;
	}
}