package com.fms.db.mapper;

import com.fms.db.model.AgentPositionTrace;
import com.fms.db.model.AgentPositionTraceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgentPositionTraceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_position_trace
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int countByExample(AgentPositionTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_position_trace
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int deleteByExample(AgentPositionTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_position_trace
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int deleteByPrimaryKey(Long blpositionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_position_trace
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int insert(AgentPositionTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_position_trace
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int insertSelective(AgentPositionTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_position_trace
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    List<AgentPositionTrace> selectByExample(AgentPositionTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_position_trace
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    AgentPositionTrace selectByPrimaryKey(Long blpositionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_position_trace
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int updateByExampleSelective(@Param("record") AgentPositionTrace record, @Param("example") AgentPositionTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_position_trace
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int updateByExample(@Param("record") AgentPositionTrace record, @Param("example") AgentPositionTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_position_trace
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int updateByPrimaryKeySelective(AgentPositionTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_position_trace
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int updateByPrimaryKey(AgentPositionTrace record);
}