package com.fms.db.mapper;

import com.fms.db.model.AgentAssessInfo;
import com.fms.db.model.AgentAssessInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgentAssessInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_assess_info
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int countByExample(AgentAssessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_assess_info
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int deleteByExample(AgentAssessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_assess_info
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int deleteByPrimaryKey(Long agentAssessInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_assess_info
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int insert(AgentAssessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_assess_info
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int insertSelective(AgentAssessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_assess_info
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    List<AgentAssessInfo> selectByExample(AgentAssessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_assess_info
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    AgentAssessInfo selectByPrimaryKey(Long agentAssessInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_assess_info
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int updateByExampleSelective(@Param("record") AgentAssessInfo record, @Param("example") AgentAssessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_assess_info
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int updateByExample(@Param("record") AgentAssessInfo record, @Param("example") AgentAssessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_assess_info
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int updateByPrimaryKeySelective(AgentAssessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_assess_info
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    int updateByPrimaryKey(AgentAssessInfo record);
}