package com.fms.db.mapper;

import com.fms.db.model.CustQuestionnaireInfo;
import com.fms.db.model.CustQuestionnaireInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustQuestionnaireInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cust_questionnaire_info
	 * @mbggenerated  Fri Jan 29 18:03:59 CST 2016
	 */
	int countByExample(CustQuestionnaireInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cust_questionnaire_info
	 * @mbggenerated  Fri Jan 29 18:03:59 CST 2016
	 */
	int deleteByExample(CustQuestionnaireInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cust_questionnaire_info
	 * @mbggenerated  Fri Jan 29 18:03:59 CST 2016
	 */
	int deleteByPrimaryKey(Long custQuestionnaireId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cust_questionnaire_info
	 * @mbggenerated  Fri Jan 29 18:03:59 CST 2016
	 */
	int insert(CustQuestionnaireInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cust_questionnaire_info
	 * @mbggenerated  Fri Jan 29 18:03:59 CST 2016
	 */
	int insertSelective(CustQuestionnaireInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cust_questionnaire_info
	 * @mbggenerated  Fri Jan 29 18:03:59 CST 2016
	 */
	List<CustQuestionnaireInfo> selectByExample(CustQuestionnaireInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cust_questionnaire_info
	 * @mbggenerated  Fri Jan 29 18:03:59 CST 2016
	 */
	CustQuestionnaireInfo selectByPrimaryKey(Long custQuestionnaireId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cust_questionnaire_info
	 * @mbggenerated  Fri Jan 29 18:03:59 CST 2016
	 */
	int updateByExampleSelective(@Param("record") CustQuestionnaireInfo record,
			@Param("example") CustQuestionnaireInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cust_questionnaire_info
	 * @mbggenerated  Fri Jan 29 18:03:59 CST 2016
	 */
	int updateByExample(@Param("record") CustQuestionnaireInfo record,
			@Param("example") CustQuestionnaireInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cust_questionnaire_info
	 * @mbggenerated  Fri Jan 29 18:03:59 CST 2016
	 */
	int updateByPrimaryKeySelective(CustQuestionnaireInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cust_questionnaire_info
	 * @mbggenerated  Fri Jan 29 18:03:59 CST 2016
	 */
	int updateByPrimaryKey(CustQuestionnaireInfo record);
}