package com.fms.db.mapper;

import com.fms.db.model.Manager;
import com.fms.db.model.ManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManagerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Thu Apr 06 15:16:30 CST 2017
	 */
	int countByExample(ManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Thu Apr 06 15:16:30 CST 2017
	 */
	int deleteByExample(ManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Thu Apr 06 15:16:30 CST 2017
	 */
	int deleteByPrimaryKey(Long managerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Thu Apr 06 15:16:30 CST 2017
	 */
	int insert(Manager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Thu Apr 06 15:16:30 CST 2017
	 */
	int insertSelective(Manager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Thu Apr 06 15:16:30 CST 2017
	 */
	List<Manager> selectByExample(ManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Thu Apr 06 15:16:30 CST 2017
	 */
	Manager selectByPrimaryKey(Long managerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Thu Apr 06 15:16:30 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Manager record, @Param("example") ManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Thu Apr 06 15:16:30 CST 2017
	 */
	int updateByExample(@Param("record") Manager record, @Param("example") ManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Thu Apr 06 15:16:30 CST 2017
	 */
	int updateByPrimaryKeySelective(Manager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbggenerated  Thu Apr 06 15:16:30 CST 2017
	 */
	int updateByPrimaryKey(Manager record);
}