package com.fms.db.mapper;

import com.fms.db.model.PDProduct;
import com.fms.db.model.PDProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PDProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pd_product
	 * @mbggenerated  Mon Apr 24 20:06:43 CST 2017
	 */
	int countByExample(PDProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pd_product
	 * @mbggenerated  Mon Apr 24 20:06:43 CST 2017
	 */
	int deleteByExample(PDProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pd_product
	 * @mbggenerated  Mon Apr 24 20:06:43 CST 2017
	 */
	int deleteByPrimaryKey(Long productId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pd_product
	 * @mbggenerated  Mon Apr 24 20:06:43 CST 2017
	 */
	int insert(PDProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pd_product
	 * @mbggenerated  Mon Apr 24 20:06:43 CST 2017
	 */
	int insertSelective(PDProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pd_product
	 * @mbggenerated  Mon Apr 24 20:06:43 CST 2017
	 */
	List<PDProduct> selectByExample(PDProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pd_product
	 * @mbggenerated  Mon Apr 24 20:06:43 CST 2017
	 */
	PDProduct selectByPrimaryKey(Long productId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pd_product
	 * @mbggenerated  Mon Apr 24 20:06:43 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PDProduct record, @Param("example") PDProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pd_product
	 * @mbggenerated  Mon Apr 24 20:06:43 CST 2017
	 */
	int updateByExample(@Param("record") PDProduct record, @Param("example") PDProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pd_product
	 * @mbggenerated  Mon Apr 24 20:06:43 CST 2017
	 */
	int updateByPrimaryKeySelective(PDProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pd_product
	 * @mbggenerated  Mon Apr 24 20:06:43 CST 2017
	 */
	int updateByPrimaryKey(PDProduct record);
	
	/**
     * 给下拉框查询商品名称
     * @param p
     * @return
     */
    List<PDProduct> getProductAllForSelect();
}