package com.fms.db.mapper;

import com.fms.db.model.TradeInfo;
import com.fms.db.model.TradeInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trade_info
	 * @mbggenerated  Tue Nov 17 14:40:57 CST 2015
	 */
	int countByExample(TradeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trade_info
	 * @mbggenerated  Tue Nov 17 14:40:57 CST 2015
	 */
	int deleteByExample(TradeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trade_info
	 * @mbggenerated  Tue Nov 17 14:40:57 CST 2015
	 */
	int deleteByPrimaryKey(Long tradeInfoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trade_info
	 * @mbggenerated  Tue Nov 17 14:40:57 CST 2015
	 */
	int insert(TradeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trade_info
	 * @mbggenerated  Tue Nov 17 14:40:57 CST 2015
	 */
	int insertSelective(TradeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trade_info
	 * @mbggenerated  Tue Nov 17 14:40:57 CST 2015
	 */
	List<TradeInfo> selectByExample(TradeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trade_info
	 * @mbggenerated  Tue Nov 17 14:40:57 CST 2015
	 */
	TradeInfo selectByPrimaryKey(Long tradeInfoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trade_info
	 * @mbggenerated  Tue Nov 17 14:40:57 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TradeInfo record, @Param("example") TradeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trade_info
	 * @mbggenerated  Tue Nov 17 14:40:57 CST 2015
	 */
	int updateByExample(@Param("record") TradeInfo record, @Param("example") TradeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trade_info
	 * @mbggenerated  Tue Nov 17 14:40:57 CST 2015
	 */
	int updateByPrimaryKeySelective(TradeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trade_info
	 * @mbggenerated  Tue Nov 17 14:40:57 CST 2015
	 */
	int updateByPrimaryKey(TradeInfo record);
}