package com.sinosoft.core.db.mapper;

import com.sinosoft.core.db.model.DefBank;
import com.sinosoft.core.db.model.DefBankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefBankMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_bank
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	int countByExample(DefBankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_bank
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	int deleteByExample(DefBankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_bank
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	int deleteByPrimaryKey(Long bankId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_bank
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	int insert(DefBank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_bank
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	int insertSelective(DefBank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_bank
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	List<DefBank> selectByExample(DefBankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_bank
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	DefBank selectByPrimaryKey(Long bankId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_bank
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	int updateByExampleSelective(@Param("record") DefBank record, @Param("example") DefBankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_bank
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	int updateByExample(@Param("record") DefBank record, @Param("example") DefBankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_bank
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	int updateByPrimaryKeySelective(DefBank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_bank
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	int updateByPrimaryKey(DefBank record);
}