package com.sinosoft.core.db.mapper;

import com.sinosoft.core.db.model.DefOccupation;
import com.sinosoft.core.db.model.DefOccupationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefOccupationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_occupation
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	int countByExample(DefOccupationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_occupation
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	int deleteByExample(DefOccupationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_occupation
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	int insert(DefOccupation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_occupation
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	int insertSelective(DefOccupation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_occupation
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	List<DefOccupation> selectByExample(DefOccupationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_occupation
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	int updateByExampleSelective(@Param("record") DefOccupation record, @Param("example") DefOccupationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_def_occupation
	 * @mbggenerated  Mon Nov 16 15:17:52 CST 2015
	 */
	int updateByExample(@Param("record") DefOccupation record, @Param("example") DefOccupationExample example);
}