package com.fms.db.model;

import java.math.BigDecimal;
import java.util.Date;

public class AgentAssess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.AGENT_ASSESS_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private Long agentAssessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.AGENT_ASSESS_INFO_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private Long agentAssessInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.COM_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private Long comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.DEPARTMENT_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private Long departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.STORE_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.AGENT_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private Long agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.BUSS_NO
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private String bussNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.TRADEINFO_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private String tradeinfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.OCCUPATION_COM_CODE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private String occupationComCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.OCCUPATION_COM_NAME
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private String occupationComName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.CUSTOMER_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.PRODUCT_CODE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.PRODUCT_NAME
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.TRADE_TYPE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.TRADE_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private Date tradeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.FOUND_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private Date foundDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.TRADE_MONEY
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private BigDecimal tradeMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.DURATION
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private String duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.DURATION_RATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private BigDecimal durationRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.SCALE_FACTOR
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private BigDecimal scaleFactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.ASSESS_FOWARDDATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private Date assessFowarddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.ASSESS_WARNDATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private Date assessWarndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.STANDARD_ASSET
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private BigDecimal standardAsset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.ASSESS_YEAR
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private String assessYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.ASSESS_MONTH
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private String assessMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.ASSESS_UNIT
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private String assessUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.ASSESS_STATUS
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private String assessStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.ASSESS_COUNT
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private String assessCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.RC_STATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private String rcState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.CREATE_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.MODIFY_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.OPER_COM_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private Long operComId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.CREATE_USER_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_agent_assess.MODIFY_USER_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    private Long modifyUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.AGENT_ASSESS_ID
     *
     * @return the value of t_agent_assess.AGENT_ASSESS_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Long getAgentAssessId() {
        return agentAssessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.AGENT_ASSESS_ID
     *
     * @param agentAssessId the value for t_agent_assess.AGENT_ASSESS_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setAgentAssessId(Long agentAssessId) {
        this.agentAssessId = agentAssessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.AGENT_ASSESS_INFO_ID
     *
     * @return the value of t_agent_assess.AGENT_ASSESS_INFO_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Long getAgentAssessInfoId() {
        return agentAssessInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.AGENT_ASSESS_INFO_ID
     *
     * @param agentAssessInfoId the value for t_agent_assess.AGENT_ASSESS_INFO_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setAgentAssessInfoId(Long agentAssessInfoId) {
        this.agentAssessInfoId = agentAssessInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.COM_ID
     *
     * @return the value of t_agent_assess.COM_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Long getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.COM_ID
     *
     * @param comId the value for t_agent_assess.COM_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setComId(Long comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.DEPARTMENT_ID
     *
     * @return the value of t_agent_assess.DEPARTMENT_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Long getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.DEPARTMENT_ID
     *
     * @param departmentId the value for t_agent_assess.DEPARTMENT_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.STORE_ID
     *
     * @return the value of t_agent_assess.STORE_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.STORE_ID
     *
     * @param storeId the value for t_agent_assess.STORE_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.AGENT_ID
     *
     * @return the value of t_agent_assess.AGENT_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Long getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.AGENT_ID
     *
     * @param agentId the value for t_agent_assess.AGENT_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setAgentId(Long agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.BUSS_NO
     *
     * @return the value of t_agent_assess.BUSS_NO
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public String getBussNo() {
        return bussNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.BUSS_NO
     *
     * @param bussNo the value for t_agent_assess.BUSS_NO
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setBussNo(String bussNo) {
        this.bussNo = bussNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.TRADEINFO_ID
     *
     * @return the value of t_agent_assess.TRADEINFO_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public String getTradeinfoId() {
        return tradeinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.TRADEINFO_ID
     *
     * @param tradeinfoId the value for t_agent_assess.TRADEINFO_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setTradeinfoId(String tradeinfoId) {
        this.tradeinfoId = tradeinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.OCCUPATION_COM_CODE
     *
     * @return the value of t_agent_assess.OCCUPATION_COM_CODE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public String getOccupationComCode() {
        return occupationComCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.OCCUPATION_COM_CODE
     *
     * @param occupationComCode the value for t_agent_assess.OCCUPATION_COM_CODE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setOccupationComCode(String occupationComCode) {
        this.occupationComCode = occupationComCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.OCCUPATION_COM_NAME
     *
     * @return the value of t_agent_assess.OCCUPATION_COM_NAME
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public String getOccupationComName() {
        return occupationComName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.OCCUPATION_COM_NAME
     *
     * @param occupationComName the value for t_agent_assess.OCCUPATION_COM_NAME
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setOccupationComName(String occupationComName) {
        this.occupationComName = occupationComName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.CUSTOMER_ID
     *
     * @return the value of t_agent_assess.CUSTOMER_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.CUSTOMER_ID
     *
     * @param customerId the value for t_agent_assess.CUSTOMER_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.PRODUCT_CODE
     *
     * @return the value of t_agent_assess.PRODUCT_CODE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.PRODUCT_CODE
     *
     * @param productCode the value for t_agent_assess.PRODUCT_CODE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.PRODUCT_NAME
     *
     * @return the value of t_agent_assess.PRODUCT_NAME
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.PRODUCT_NAME
     *
     * @param productName the value for t_agent_assess.PRODUCT_NAME
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.TRADE_TYPE
     *
     * @return the value of t_agent_assess.TRADE_TYPE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.TRADE_TYPE
     *
     * @param tradeType the value for t_agent_assess.TRADE_TYPE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.TRADE_DATE
     *
     * @return the value of t_agent_assess.TRADE_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Date getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.TRADE_DATE
     *
     * @param tradeDate the value for t_agent_assess.TRADE_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setTradeDate(Date tradeDate) {
        this.tradeDate = tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.FOUND_DATE
     *
     * @return the value of t_agent_assess.FOUND_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Date getFoundDate() {
        return foundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.FOUND_DATE
     *
     * @param foundDate the value for t_agent_assess.FOUND_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setFoundDate(Date foundDate) {
        this.foundDate = foundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.TRADE_MONEY
     *
     * @return the value of t_agent_assess.TRADE_MONEY
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public BigDecimal getTradeMoney() {
        return tradeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.TRADE_MONEY
     *
     * @param tradeMoney the value for t_agent_assess.TRADE_MONEY
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setTradeMoney(BigDecimal tradeMoney) {
        this.tradeMoney = tradeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.DURATION
     *
     * @return the value of t_agent_assess.DURATION
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.DURATION
     *
     * @param duration the value for t_agent_assess.DURATION
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setDuration(String duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.DURATION_RATE
     *
     * @return the value of t_agent_assess.DURATION_RATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public BigDecimal getDurationRate() {
        return durationRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.DURATION_RATE
     *
     * @param durationRate the value for t_agent_assess.DURATION_RATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setDurationRate(BigDecimal durationRate) {
        this.durationRate = durationRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.SCALE_FACTOR
     *
     * @return the value of t_agent_assess.SCALE_FACTOR
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public BigDecimal getScaleFactor() {
        return scaleFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.SCALE_FACTOR
     *
     * @param scaleFactor the value for t_agent_assess.SCALE_FACTOR
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setScaleFactor(BigDecimal scaleFactor) {
        this.scaleFactor = scaleFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.ASSESS_FOWARDDATE
     *
     * @return the value of t_agent_assess.ASSESS_FOWARDDATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Date getAssessFowarddate() {
        return assessFowarddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.ASSESS_FOWARDDATE
     *
     * @param assessFowarddate the value for t_agent_assess.ASSESS_FOWARDDATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setAssessFowarddate(Date assessFowarddate) {
        this.assessFowarddate = assessFowarddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.ASSESS_WARNDATE
     *
     * @return the value of t_agent_assess.ASSESS_WARNDATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Date getAssessWarndate() {
        return assessWarndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.ASSESS_WARNDATE
     *
     * @param assessWarndate the value for t_agent_assess.ASSESS_WARNDATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setAssessWarndate(Date assessWarndate) {
        this.assessWarndate = assessWarndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.STANDARD_ASSET
     *
     * @return the value of t_agent_assess.STANDARD_ASSET
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public BigDecimal getStandardAsset() {
        return standardAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.STANDARD_ASSET
     *
     * @param standardAsset the value for t_agent_assess.STANDARD_ASSET
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setStandardAsset(BigDecimal standardAsset) {
        this.standardAsset = standardAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.ASSESS_YEAR
     *
     * @return the value of t_agent_assess.ASSESS_YEAR
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public String getAssessYear() {
        return assessYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.ASSESS_YEAR
     *
     * @param assessYear the value for t_agent_assess.ASSESS_YEAR
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setAssessYear(String assessYear) {
        this.assessYear = assessYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.ASSESS_MONTH
     *
     * @return the value of t_agent_assess.ASSESS_MONTH
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public String getAssessMonth() {
        return assessMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.ASSESS_MONTH
     *
     * @param assessMonth the value for t_agent_assess.ASSESS_MONTH
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setAssessMonth(String assessMonth) {
        this.assessMonth = assessMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.ASSESS_UNIT
     *
     * @return the value of t_agent_assess.ASSESS_UNIT
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public String getAssessUnit() {
        return assessUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.ASSESS_UNIT
     *
     * @param assessUnit the value for t_agent_assess.ASSESS_UNIT
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setAssessUnit(String assessUnit) {
        this.assessUnit = assessUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.ASSESS_STATUS
     *
     * @return the value of t_agent_assess.ASSESS_STATUS
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public String getAssessStatus() {
        return assessStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.ASSESS_STATUS
     *
     * @param assessStatus the value for t_agent_assess.ASSESS_STATUS
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setAssessStatus(String assessStatus) {
        this.assessStatus = assessStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.ASSESS_COUNT
     *
     * @return the value of t_agent_assess.ASSESS_COUNT
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public String getAssessCount() {
        return assessCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.ASSESS_COUNT
     *
     * @param assessCount the value for t_agent_assess.ASSESS_COUNT
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setAssessCount(String assessCount) {
        this.assessCount = assessCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.RC_STATE
     *
     * @return the value of t_agent_assess.RC_STATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public String getRcState() {
        return rcState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.RC_STATE
     *
     * @param rcState the value for t_agent_assess.RC_STATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setRcState(String rcState) {
        this.rcState = rcState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.CREATE_DATE
     *
     * @return the value of t_agent_assess.CREATE_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.CREATE_DATE
     *
     * @param createDate the value for t_agent_assess.CREATE_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.MODIFY_DATE
     *
     * @return the value of t_agent_assess.MODIFY_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.MODIFY_DATE
     *
     * @param modifyDate the value for t_agent_assess.MODIFY_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.OPER_COM_ID
     *
     * @return the value of t_agent_assess.OPER_COM_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Long getOperComId() {
        return operComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.OPER_COM_ID
     *
     * @param operComId the value for t_agent_assess.OPER_COM_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setOperComId(Long operComId) {
        this.operComId = operComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.CREATE_USER_ID
     *
     * @return the value of t_agent_assess.CREATE_USER_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.CREATE_USER_ID
     *
     * @param createUserId the value for t_agent_assess.CREATE_USER_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_agent_assess.MODIFY_USER_ID
     *
     * @return the value of t_agent_assess.MODIFY_USER_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Long getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_agent_assess.MODIFY_USER_ID
     *
     * @param modifyUserId the value for t_agent_assess.MODIFY_USER_ID
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setModifyUserId(Long modifyUserId) {
        this.modifyUserId = modifyUserId;
    }
}