package com.fms.db.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AgentWageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_agent_wage
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_agent_wage
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_agent_wage
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_wage
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public AgentWageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_wage
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_wage
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_wage
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_wage
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_wage
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_wage
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_wage
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_wage
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_wage
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agent_wage
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_agent_wage
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andAgentWageCalIdIsNull() {
            addCriterion("AGENT_WAGE_CAL_ID is null");
            return (Criteria) this;
        }

        public Criteria andAgentWageCalIdIsNotNull() {
            addCriterion("AGENT_WAGE_CAL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAgentWageCalIdEqualTo(Long value) {
            addCriterion("AGENT_WAGE_CAL_ID =", value, "agentWageCalId");
            return (Criteria) this;
        }

        public Criteria andAgentWageCalIdNotEqualTo(Long value) {
            addCriterion("AGENT_WAGE_CAL_ID <>", value, "agentWageCalId");
            return (Criteria) this;
        }

        public Criteria andAgentWageCalIdGreaterThan(Long value) {
            addCriterion("AGENT_WAGE_CAL_ID >", value, "agentWageCalId");
            return (Criteria) this;
        }

        public Criteria andAgentWageCalIdGreaterThanOrEqualTo(Long value) {
            addCriterion("AGENT_WAGE_CAL_ID >=", value, "agentWageCalId");
            return (Criteria) this;
        }

        public Criteria andAgentWageCalIdLessThan(Long value) {
            addCriterion("AGENT_WAGE_CAL_ID <", value, "agentWageCalId");
            return (Criteria) this;
        }

        public Criteria andAgentWageCalIdLessThanOrEqualTo(Long value) {
            addCriterion("AGENT_WAGE_CAL_ID <=", value, "agentWageCalId");
            return (Criteria) this;
        }

        public Criteria andAgentWageCalIdIn(List<Long> values) {
            addCriterion("AGENT_WAGE_CAL_ID in", values, "agentWageCalId");
            return (Criteria) this;
        }

        public Criteria andAgentWageCalIdNotIn(List<Long> values) {
            addCriterion("AGENT_WAGE_CAL_ID not in", values, "agentWageCalId");
            return (Criteria) this;
        }

        public Criteria andAgentWageCalIdBetween(Long value1, Long value2) {
            addCriterion("AGENT_WAGE_CAL_ID between", value1, value2, "agentWageCalId");
            return (Criteria) this;
        }

        public Criteria andAgentWageCalIdNotBetween(Long value1, Long value2) {
            addCriterion("AGENT_WAGE_CAL_ID not between", value1, value2, "agentWageCalId");
            return (Criteria) this;
        }

        public Criteria andTradeinfoIdIsNull() {
            addCriterion("TRADEINFO_ID is null");
            return (Criteria) this;
        }

        public Criteria andTradeinfoIdIsNotNull() {
            addCriterion("TRADEINFO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTradeinfoIdEqualTo(String value) {
            addCriterion("TRADEINFO_ID =", value, "tradeinfoId");
            return (Criteria) this;
        }

        public Criteria andTradeinfoIdNotEqualTo(String value) {
            addCriterion("TRADEINFO_ID <>", value, "tradeinfoId");
            return (Criteria) this;
        }

        public Criteria andTradeinfoIdGreaterThan(String value) {
            addCriterion("TRADEINFO_ID >", value, "tradeinfoId");
            return (Criteria) this;
        }

        public Criteria andTradeinfoIdGreaterThanOrEqualTo(String value) {
            addCriterion("TRADEINFO_ID >=", value, "tradeinfoId");
            return (Criteria) this;
        }

        public Criteria andTradeinfoIdLessThan(String value) {
            addCriterion("TRADEINFO_ID <", value, "tradeinfoId");
            return (Criteria) this;
        }

        public Criteria andTradeinfoIdLessThanOrEqualTo(String value) {
            addCriterion("TRADEINFO_ID <=", value, "tradeinfoId");
            return (Criteria) this;
        }

        public Criteria andTradeinfoIdLike(String value) {
            addCriterion("TRADEINFO_ID like", value, "tradeinfoId");
            return (Criteria) this;
        }

        public Criteria andTradeinfoIdNotLike(String value) {
            addCriterion("TRADEINFO_ID not like", value, "tradeinfoId");
            return (Criteria) this;
        }

        public Criteria andTradeinfoIdIn(List<String> values) {
            addCriterion("TRADEINFO_ID in", values, "tradeinfoId");
            return (Criteria) this;
        }

        public Criteria andTradeinfoIdNotIn(List<String> values) {
            addCriterion("TRADEINFO_ID not in", values, "tradeinfoId");
            return (Criteria) this;
        }

        public Criteria andTradeinfoIdBetween(String value1, String value2) {
            addCriterion("TRADEINFO_ID between", value1, value2, "tradeinfoId");
            return (Criteria) this;
        }

        public Criteria andTradeinfoIdNotBetween(String value1, String value2) {
            addCriterion("TRADEINFO_ID not between", value1, value2, "tradeinfoId");
            return (Criteria) this;
        }

        public Criteria andBussNoIsNull() {
            addCriterion("BUSS_NO is null");
            return (Criteria) this;
        }

        public Criteria andBussNoIsNotNull() {
            addCriterion("BUSS_NO is not null");
            return (Criteria) this;
        }

        public Criteria andBussNoEqualTo(String value) {
            addCriterion("BUSS_NO =", value, "bussNo");
            return (Criteria) this;
        }

        public Criteria andBussNoNotEqualTo(String value) {
            addCriterion("BUSS_NO <>", value, "bussNo");
            return (Criteria) this;
        }

        public Criteria andBussNoGreaterThan(String value) {
            addCriterion("BUSS_NO >", value, "bussNo");
            return (Criteria) this;
        }

        public Criteria andBussNoGreaterThanOrEqualTo(String value) {
            addCriterion("BUSS_NO >=", value, "bussNo");
            return (Criteria) this;
        }

        public Criteria andBussNoLessThan(String value) {
            addCriterion("BUSS_NO <", value, "bussNo");
            return (Criteria) this;
        }

        public Criteria andBussNoLessThanOrEqualTo(String value) {
            addCriterion("BUSS_NO <=", value, "bussNo");
            return (Criteria) this;
        }

        public Criteria andBussNoLike(String value) {
            addCriterion("BUSS_NO like", value, "bussNo");
            return (Criteria) this;
        }

        public Criteria andBussNoNotLike(String value) {
            addCriterion("BUSS_NO not like", value, "bussNo");
            return (Criteria) this;
        }

        public Criteria andBussNoIn(List<String> values) {
            addCriterion("BUSS_NO in", values, "bussNo");
            return (Criteria) this;
        }

        public Criteria andBussNoNotIn(List<String> values) {
            addCriterion("BUSS_NO not in", values, "bussNo");
            return (Criteria) this;
        }

        public Criteria andBussNoBetween(String value1, String value2) {
            addCriterion("BUSS_NO between", value1, value2, "bussNo");
            return (Criteria) this;
        }

        public Criteria andBussNoNotBetween(String value1, String value2) {
            addCriterion("BUSS_NO not between", value1, value2, "bussNo");
            return (Criteria) this;
        }

        public Criteria andAgentIdIsNull() {
            addCriterion("AGENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andAgentIdIsNotNull() {
            addCriterion("AGENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAgentIdEqualTo(Long value) {
            addCriterion("AGENT_ID =", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdNotEqualTo(Long value) {
            addCriterion("AGENT_ID <>", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdGreaterThan(Long value) {
            addCriterion("AGENT_ID >", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("AGENT_ID >=", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdLessThan(Long value) {
            addCriterion("AGENT_ID <", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdLessThanOrEqualTo(Long value) {
            addCriterion("AGENT_ID <=", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdIn(List<Long> values) {
            addCriterion("AGENT_ID in", values, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdNotIn(List<Long> values) {
            addCriterion("AGENT_ID not in", values, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdBetween(Long value1, Long value2) {
            addCriterion("AGENT_ID between", value1, value2, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdNotBetween(Long value1, Long value2) {
            addCriterion("AGENT_ID not between", value1, value2, "agentId");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIsNull() {
            addCriterion("TRADE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIsNotNull() {
            addCriterion("TRADE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTradeTypeEqualTo(String value) {
            addCriterion("TRADE_TYPE =", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotEqualTo(String value) {
            addCriterion("TRADE_TYPE <>", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeGreaterThan(String value) {
            addCriterion("TRADE_TYPE >", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_TYPE >=", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLessThan(String value) {
            addCriterion("TRADE_TYPE <", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLessThanOrEqualTo(String value) {
            addCriterion("TRADE_TYPE <=", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLike(String value) {
            addCriterion("TRADE_TYPE like", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotLike(String value) {
            addCriterion("TRADE_TYPE not like", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIn(List<String> values) {
            addCriterion("TRADE_TYPE in", values, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotIn(List<String> values) {
            addCriterion("TRADE_TYPE not in", values, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeBetween(String value1, String value2) {
            addCriterion("TRADE_TYPE between", value1, value2, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotBetween(String value1, String value2) {
            addCriterion("TRADE_TYPE not between", value1, value2, "tradeType");
            return (Criteria) this;
        }

        public Criteria andOccupationComCodeIsNull() {
            addCriterion("OCCUPATION_COM_CODE is null");
            return (Criteria) this;
        }

        public Criteria andOccupationComCodeIsNotNull() {
            addCriterion("OCCUPATION_COM_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andOccupationComCodeEqualTo(String value) {
            addCriterion("OCCUPATION_COM_CODE =", value, "occupationComCode");
            return (Criteria) this;
        }

        public Criteria andOccupationComCodeNotEqualTo(String value) {
            addCriterion("OCCUPATION_COM_CODE <>", value, "occupationComCode");
            return (Criteria) this;
        }

        public Criteria andOccupationComCodeGreaterThan(String value) {
            addCriterion("OCCUPATION_COM_CODE >", value, "occupationComCode");
            return (Criteria) this;
        }

        public Criteria andOccupationComCodeGreaterThanOrEqualTo(String value) {
            addCriterion("OCCUPATION_COM_CODE >=", value, "occupationComCode");
            return (Criteria) this;
        }

        public Criteria andOccupationComCodeLessThan(String value) {
            addCriterion("OCCUPATION_COM_CODE <", value, "occupationComCode");
            return (Criteria) this;
        }

        public Criteria andOccupationComCodeLessThanOrEqualTo(String value) {
            addCriterion("OCCUPATION_COM_CODE <=", value, "occupationComCode");
            return (Criteria) this;
        }

        public Criteria andOccupationComCodeLike(String value) {
            addCriterion("OCCUPATION_COM_CODE like", value, "occupationComCode");
            return (Criteria) this;
        }

        public Criteria andOccupationComCodeNotLike(String value) {
            addCriterion("OCCUPATION_COM_CODE not like", value, "occupationComCode");
            return (Criteria) this;
        }

        public Criteria andOccupationComCodeIn(List<String> values) {
            addCriterion("OCCUPATION_COM_CODE in", values, "occupationComCode");
            return (Criteria) this;
        }

        public Criteria andOccupationComCodeNotIn(List<String> values) {
            addCriterion("OCCUPATION_COM_CODE not in", values, "occupationComCode");
            return (Criteria) this;
        }

        public Criteria andOccupationComCodeBetween(String value1, String value2) {
            addCriterion("OCCUPATION_COM_CODE between", value1, value2, "occupationComCode");
            return (Criteria) this;
        }

        public Criteria andOccupationComCodeNotBetween(String value1, String value2) {
            addCriterion("OCCUPATION_COM_CODE not between", value1, value2, "occupationComCode");
            return (Criteria) this;
        }

        public Criteria andOccupationComNameIsNull() {
            addCriterion("OCCUPATION_COM_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOccupationComNameIsNotNull() {
            addCriterion("OCCUPATION_COM_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOccupationComNameEqualTo(String value) {
            addCriterion("OCCUPATION_COM_NAME =", value, "occupationComName");
            return (Criteria) this;
        }

        public Criteria andOccupationComNameNotEqualTo(String value) {
            addCriterion("OCCUPATION_COM_NAME <>", value, "occupationComName");
            return (Criteria) this;
        }

        public Criteria andOccupationComNameGreaterThan(String value) {
            addCriterion("OCCUPATION_COM_NAME >", value, "occupationComName");
            return (Criteria) this;
        }

        public Criteria andOccupationComNameGreaterThanOrEqualTo(String value) {
            addCriterion("OCCUPATION_COM_NAME >=", value, "occupationComName");
            return (Criteria) this;
        }

        public Criteria andOccupationComNameLessThan(String value) {
            addCriterion("OCCUPATION_COM_NAME <", value, "occupationComName");
            return (Criteria) this;
        }

        public Criteria andOccupationComNameLessThanOrEqualTo(String value) {
            addCriterion("OCCUPATION_COM_NAME <=", value, "occupationComName");
            return (Criteria) this;
        }

        public Criteria andOccupationComNameLike(String value) {
            addCriterion("OCCUPATION_COM_NAME like", value, "occupationComName");
            return (Criteria) this;
        }

        public Criteria andOccupationComNameNotLike(String value) {
            addCriterion("OCCUPATION_COM_NAME not like", value, "occupationComName");
            return (Criteria) this;
        }

        public Criteria andOccupationComNameIn(List<String> values) {
            addCriterion("OCCUPATION_COM_NAME in", values, "occupationComName");
            return (Criteria) this;
        }

        public Criteria andOccupationComNameNotIn(List<String> values) {
            addCriterion("OCCUPATION_COM_NAME not in", values, "occupationComName");
            return (Criteria) this;
        }

        public Criteria andOccupationComNameBetween(String value1, String value2) {
            addCriterion("OCCUPATION_COM_NAME between", value1, value2, "occupationComName");
            return (Criteria) this;
        }

        public Criteria andOccupationComNameNotBetween(String value1, String value2) {
            addCriterion("OCCUPATION_COM_NAME not between", value1, value2, "occupationComName");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNull() {
            addCriterion("PRODUCT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNotNull() {
            addCriterion("PRODUCT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andProductCodeEqualTo(String value) {
            addCriterion("PRODUCT_CODE =", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotEqualTo(String value) {
            addCriterion("PRODUCT_CODE <>", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThan(String value) {
            addCriterion("PRODUCT_CODE >", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_CODE >=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThan(String value) {
            addCriterion("PRODUCT_CODE <", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_CODE <=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLike(String value) {
            addCriterion("PRODUCT_CODE like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotLike(String value) {
            addCriterion("PRODUCT_CODE not like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeIn(List<String> values) {
            addCriterion("PRODUCT_CODE in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotIn(List<String> values) {
            addCriterion("PRODUCT_CODE not in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeBetween(String value1, String value2) {
            addCriterion("PRODUCT_CODE between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_CODE not between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("PRODUCT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("PRODUCT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("PRODUCT_NAME =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("PRODUCT_NAME <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("PRODUCT_NAME >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_NAME >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("PRODUCT_NAME <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_NAME <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("PRODUCT_NAME like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("PRODUCT_NAME not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("PRODUCT_NAME in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("PRODUCT_NAME not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("PRODUCT_NAME between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_NAME not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andComIdIsNull() {
            addCriterion("COM_ID is null");
            return (Criteria) this;
        }

        public Criteria andComIdIsNotNull() {
            addCriterion("COM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andComIdEqualTo(Long value) {
            addCriterion("COM_ID =", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotEqualTo(Long value) {
            addCriterion("COM_ID <>", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdGreaterThan(Long value) {
            addCriterion("COM_ID >", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdGreaterThanOrEqualTo(Long value) {
            addCriterion("COM_ID >=", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdLessThan(Long value) {
            addCriterion("COM_ID <", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdLessThanOrEqualTo(Long value) {
            addCriterion("COM_ID <=", value, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdIn(List<Long> values) {
            addCriterion("COM_ID in", values, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotIn(List<Long> values) {
            addCriterion("COM_ID not in", values, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdBetween(Long value1, Long value2) {
            addCriterion("COM_ID between", value1, value2, "comId");
            return (Criteria) this;
        }

        public Criteria andComIdNotBetween(Long value1, Long value2) {
            addCriterion("COM_ID not between", value1, value2, "comId");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNull() {
            addCriterion("STORE_ID is null");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNotNull() {
            addCriterion("STORE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andStoreIdEqualTo(Long value) {
            addCriterion("STORE_ID =", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotEqualTo(Long value) {
            addCriterion("STORE_ID <>", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThan(Long value) {
            addCriterion("STORE_ID >", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThanOrEqualTo(Long value) {
            addCriterion("STORE_ID >=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThan(Long value) {
            addCriterion("STORE_ID <", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThanOrEqualTo(Long value) {
            addCriterion("STORE_ID <=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdIn(List<Long> values) {
            addCriterion("STORE_ID in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotIn(List<Long> values) {
            addCriterion("STORE_ID not in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdBetween(Long value1, Long value2) {
            addCriterion("STORE_ID between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotBetween(Long value1, Long value2) {
            addCriterion("STORE_ID not between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNull() {
            addCriterion("CUSTOMER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNotNull() {
            addCriterion("CUSTOMER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdEqualTo(Long value) {
            addCriterion("CUSTOMER_ID =", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotEqualTo(Long value) {
            addCriterion("CUSTOMER_ID <>", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThan(Long value) {
            addCriterion("CUSTOMER_ID >", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("CUSTOMER_ID >=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThan(Long value) {
            addCriterion("CUSTOMER_ID <", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThanOrEqualTo(Long value) {
            addCriterion("CUSTOMER_ID <=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIn(List<Long> values) {
            addCriterion("CUSTOMER_ID in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotIn(List<Long> values) {
            addCriterion("CUSTOMER_ID not in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdBetween(Long value1, Long value2) {
            addCriterion("CUSTOMER_ID between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotBetween(Long value1, Long value2) {
            addCriterion("CUSTOMER_ID not between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andTradeMoneyIsNull() {
            addCriterion("TRADE_MONEY is null");
            return (Criteria) this;
        }

        public Criteria andTradeMoneyIsNotNull() {
            addCriterion("TRADE_MONEY is not null");
            return (Criteria) this;
        }

        public Criteria andTradeMoneyEqualTo(BigDecimal value) {
            addCriterion("TRADE_MONEY =", value, "tradeMoney");
            return (Criteria) this;
        }

        public Criteria andTradeMoneyNotEqualTo(BigDecimal value) {
            addCriterion("TRADE_MONEY <>", value, "tradeMoney");
            return (Criteria) this;
        }

        public Criteria andTradeMoneyGreaterThan(BigDecimal value) {
            addCriterion("TRADE_MONEY >", value, "tradeMoney");
            return (Criteria) this;
        }

        public Criteria andTradeMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TRADE_MONEY >=", value, "tradeMoney");
            return (Criteria) this;
        }

        public Criteria andTradeMoneyLessThan(BigDecimal value) {
            addCriterion("TRADE_MONEY <", value, "tradeMoney");
            return (Criteria) this;
        }

        public Criteria andTradeMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TRADE_MONEY <=", value, "tradeMoney");
            return (Criteria) this;
        }

        public Criteria andTradeMoneyIn(List<BigDecimal> values) {
            addCriterion("TRADE_MONEY in", values, "tradeMoney");
            return (Criteria) this;
        }

        public Criteria andTradeMoneyNotIn(List<BigDecimal> values) {
            addCriterion("TRADE_MONEY not in", values, "tradeMoney");
            return (Criteria) this;
        }

        public Criteria andTradeMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRADE_MONEY between", value1, value2, "tradeMoney");
            return (Criteria) this;
        }

        public Criteria andTradeMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRADE_MONEY not between", value1, value2, "tradeMoney");
            return (Criteria) this;
        }

        public Criteria andWageValueIsNull() {
            addCriterion("WAGE_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andWageValueIsNotNull() {
            addCriterion("WAGE_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andWageValueEqualTo(BigDecimal value) {
            addCriterion("WAGE_VALUE =", value, "wageValue");
            return (Criteria) this;
        }

        public Criteria andWageValueNotEqualTo(BigDecimal value) {
            addCriterion("WAGE_VALUE <>", value, "wageValue");
            return (Criteria) this;
        }

        public Criteria andWageValueGreaterThan(BigDecimal value) {
            addCriterion("WAGE_VALUE >", value, "wageValue");
            return (Criteria) this;
        }

        public Criteria andWageValueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("WAGE_VALUE >=", value, "wageValue");
            return (Criteria) this;
        }

        public Criteria andWageValueLessThan(BigDecimal value) {
            addCriterion("WAGE_VALUE <", value, "wageValue");
            return (Criteria) this;
        }

        public Criteria andWageValueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("WAGE_VALUE <=", value, "wageValue");
            return (Criteria) this;
        }

        public Criteria andWageValueIn(List<BigDecimal> values) {
            addCriterion("WAGE_VALUE in", values, "wageValue");
            return (Criteria) this;
        }

        public Criteria andWageValueNotIn(List<BigDecimal> values) {
            addCriterion("WAGE_VALUE not in", values, "wageValue");
            return (Criteria) this;
        }

        public Criteria andWageValueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("WAGE_VALUE between", value1, value2, "wageValue");
            return (Criteria) this;
        }

        public Criteria andWageValueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("WAGE_VALUE not between", value1, value2, "wageValue");
            return (Criteria) this;
        }

        public Criteria andWageStateIsNull() {
            addCriterion("WAGE_STATE is null");
            return (Criteria) this;
        }

        public Criteria andWageStateIsNotNull() {
            addCriterion("WAGE_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andWageStateEqualTo(String value) {
            addCriterion("WAGE_STATE =", value, "wageState");
            return (Criteria) this;
        }

        public Criteria andWageStateNotEqualTo(String value) {
            addCriterion("WAGE_STATE <>", value, "wageState");
            return (Criteria) this;
        }

        public Criteria andWageStateGreaterThan(String value) {
            addCriterion("WAGE_STATE >", value, "wageState");
            return (Criteria) this;
        }

        public Criteria andWageStateGreaterThanOrEqualTo(String value) {
            addCriterion("WAGE_STATE >=", value, "wageState");
            return (Criteria) this;
        }

        public Criteria andWageStateLessThan(String value) {
            addCriterion("WAGE_STATE <", value, "wageState");
            return (Criteria) this;
        }

        public Criteria andWageStateLessThanOrEqualTo(String value) {
            addCriterion("WAGE_STATE <=", value, "wageState");
            return (Criteria) this;
        }

        public Criteria andWageStateLike(String value) {
            addCriterion("WAGE_STATE like", value, "wageState");
            return (Criteria) this;
        }

        public Criteria andWageStateNotLike(String value) {
            addCriterion("WAGE_STATE not like", value, "wageState");
            return (Criteria) this;
        }

        public Criteria andWageStateIn(List<String> values) {
            addCriterion("WAGE_STATE in", values, "wageState");
            return (Criteria) this;
        }

        public Criteria andWageStateNotIn(List<String> values) {
            addCriterion("WAGE_STATE not in", values, "wageState");
            return (Criteria) this;
        }

        public Criteria andWageStateBetween(String value1, String value2) {
            addCriterion("WAGE_STATE between", value1, value2, "wageState");
            return (Criteria) this;
        }

        public Criteria andWageStateNotBetween(String value1, String value2) {
            addCriterion("WAGE_STATE not between", value1, value2, "wageState");
            return (Criteria) this;
        }

        public Criteria andPayStateIsNull() {
            addCriterion("PAY_STATE is null");
            return (Criteria) this;
        }

        public Criteria andPayStateIsNotNull() {
            addCriterion("PAY_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andPayStateEqualTo(String value) {
            addCriterion("PAY_STATE =", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateNotEqualTo(String value) {
            addCriterion("PAY_STATE <>", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateGreaterThan(String value) {
            addCriterion("PAY_STATE >", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_STATE >=", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateLessThan(String value) {
            addCriterion("PAY_STATE <", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateLessThanOrEqualTo(String value) {
            addCriterion("PAY_STATE <=", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateLike(String value) {
            addCriterion("PAY_STATE like", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateNotLike(String value) {
            addCriterion("PAY_STATE not like", value, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateIn(List<String> values) {
            addCriterion("PAY_STATE in", values, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateNotIn(List<String> values) {
            addCriterion("PAY_STATE not in", values, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateBetween(String value1, String value2) {
            addCriterion("PAY_STATE between", value1, value2, "payState");
            return (Criteria) this;
        }

        public Criteria andPayStateNotBetween(String value1, String value2) {
            addCriterion("PAY_STATE not between", value1, value2, "payState");
            return (Criteria) this;
        }

        public Criteria andTradeDateIsNull() {
            addCriterion("TRADE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTradeDateIsNotNull() {
            addCriterion("TRADE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTradeDateEqualTo(Date value) {
            addCriterionForJDBCDate("TRADE_DATE =", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("TRADE_DATE <>", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateGreaterThan(Date value) {
            addCriterionForJDBCDate("TRADE_DATE >", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("TRADE_DATE >=", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateLessThan(Date value) {
            addCriterionForJDBCDate("TRADE_DATE <", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("TRADE_DATE <=", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateIn(List<Date> values) {
            addCriterionForJDBCDate("TRADE_DATE in", values, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("TRADE_DATE not in", values, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("TRADE_DATE between", value1, value2, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("TRADE_DATE not between", value1, value2, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andCalYearIsNull() {
            addCriterion("CAL_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andCalYearIsNotNull() {
            addCriterion("CAL_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andCalYearEqualTo(String value) {
            addCriterion("CAL_YEAR =", value, "calYear");
            return (Criteria) this;
        }

        public Criteria andCalYearNotEqualTo(String value) {
            addCriterion("CAL_YEAR <>", value, "calYear");
            return (Criteria) this;
        }

        public Criteria andCalYearGreaterThan(String value) {
            addCriterion("CAL_YEAR >", value, "calYear");
            return (Criteria) this;
        }

        public Criteria andCalYearGreaterThanOrEqualTo(String value) {
            addCriterion("CAL_YEAR >=", value, "calYear");
            return (Criteria) this;
        }

        public Criteria andCalYearLessThan(String value) {
            addCriterion("CAL_YEAR <", value, "calYear");
            return (Criteria) this;
        }

        public Criteria andCalYearLessThanOrEqualTo(String value) {
            addCriterion("CAL_YEAR <=", value, "calYear");
            return (Criteria) this;
        }

        public Criteria andCalYearLike(String value) {
            addCriterion("CAL_YEAR like", value, "calYear");
            return (Criteria) this;
        }

        public Criteria andCalYearNotLike(String value) {
            addCriterion("CAL_YEAR not like", value, "calYear");
            return (Criteria) this;
        }

        public Criteria andCalYearIn(List<String> values) {
            addCriterion("CAL_YEAR in", values, "calYear");
            return (Criteria) this;
        }

        public Criteria andCalYearNotIn(List<String> values) {
            addCriterion("CAL_YEAR not in", values, "calYear");
            return (Criteria) this;
        }

        public Criteria andCalYearBetween(String value1, String value2) {
            addCriterion("CAL_YEAR between", value1, value2, "calYear");
            return (Criteria) this;
        }

        public Criteria andCalYearNotBetween(String value1, String value2) {
            addCriterion("CAL_YEAR not between", value1, value2, "calYear");
            return (Criteria) this;
        }

        public Criteria andCalMonthIsNull() {
            addCriterion("CAL_MONTH is null");
            return (Criteria) this;
        }

        public Criteria andCalMonthIsNotNull() {
            addCriterion("CAL_MONTH is not null");
            return (Criteria) this;
        }

        public Criteria andCalMonthEqualTo(String value) {
            addCriterion("CAL_MONTH =", value, "calMonth");
            return (Criteria) this;
        }

        public Criteria andCalMonthNotEqualTo(String value) {
            addCriterion("CAL_MONTH <>", value, "calMonth");
            return (Criteria) this;
        }

        public Criteria andCalMonthGreaterThan(String value) {
            addCriterion("CAL_MONTH >", value, "calMonth");
            return (Criteria) this;
        }

        public Criteria andCalMonthGreaterThanOrEqualTo(String value) {
            addCriterion("CAL_MONTH >=", value, "calMonth");
            return (Criteria) this;
        }

        public Criteria andCalMonthLessThan(String value) {
            addCriterion("CAL_MONTH <", value, "calMonth");
            return (Criteria) this;
        }

        public Criteria andCalMonthLessThanOrEqualTo(String value) {
            addCriterion("CAL_MONTH <=", value, "calMonth");
            return (Criteria) this;
        }

        public Criteria andCalMonthLike(String value) {
            addCriterion("CAL_MONTH like", value, "calMonth");
            return (Criteria) this;
        }

        public Criteria andCalMonthNotLike(String value) {
            addCriterion("CAL_MONTH not like", value, "calMonth");
            return (Criteria) this;
        }

        public Criteria andCalMonthIn(List<String> values) {
            addCriterion("CAL_MONTH in", values, "calMonth");
            return (Criteria) this;
        }

        public Criteria andCalMonthNotIn(List<String> values) {
            addCriterion("CAL_MONTH not in", values, "calMonth");
            return (Criteria) this;
        }

        public Criteria andCalMonthBetween(String value1, String value2) {
            addCriterion("CAL_MONTH between", value1, value2, "calMonth");
            return (Criteria) this;
        }

        public Criteria andCalMonthNotBetween(String value1, String value2) {
            addCriterion("CAL_MONTH not between", value1, value2, "calMonth");
            return (Criteria) this;
        }

        public Criteria andRcStateIsNull() {
            addCriterion("RC_STATE is null");
            return (Criteria) this;
        }

        public Criteria andRcStateIsNotNull() {
            addCriterion("RC_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andRcStateEqualTo(String value) {
            addCriterion("RC_STATE =", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateNotEqualTo(String value) {
            addCriterion("RC_STATE <>", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateGreaterThan(String value) {
            addCriterion("RC_STATE >", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateGreaterThanOrEqualTo(String value) {
            addCriterion("RC_STATE >=", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateLessThan(String value) {
            addCriterion("RC_STATE <", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateLessThanOrEqualTo(String value) {
            addCriterion("RC_STATE <=", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateLike(String value) {
            addCriterion("RC_STATE like", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateNotLike(String value) {
            addCriterion("RC_STATE not like", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateIn(List<String> values) {
            addCriterion("RC_STATE in", values, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateNotIn(List<String> values) {
            addCriterion("RC_STATE not in", values, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateBetween(String value1, String value2) {
            addCriterion("RC_STATE between", value1, value2, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateNotBetween(String value1, String value2) {
            addCriterion("RC_STATE not between", value1, value2, "rcState");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("MODIFY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("MODIFY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("MODIFY_DATE =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("MODIFY_DATE <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("MODIFY_DATE >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("MODIFY_DATE <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("MODIFY_DATE in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("MODIFY_DATE not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andOperComIdIsNull() {
            addCriterion("OPER_COM_ID is null");
            return (Criteria) this;
        }

        public Criteria andOperComIdIsNotNull() {
            addCriterion("OPER_COM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOperComIdEqualTo(Long value) {
            addCriterion("OPER_COM_ID =", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdNotEqualTo(Long value) {
            addCriterion("OPER_COM_ID <>", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdGreaterThan(Long value) {
            addCriterion("OPER_COM_ID >", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdGreaterThanOrEqualTo(Long value) {
            addCriterion("OPER_COM_ID >=", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdLessThan(Long value) {
            addCriterion("OPER_COM_ID <", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdLessThanOrEqualTo(Long value) {
            addCriterion("OPER_COM_ID <=", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdIn(List<Long> values) {
            addCriterion("OPER_COM_ID in", values, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdNotIn(List<Long> values) {
            addCriterion("OPER_COM_ID not in", values, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdBetween(Long value1, Long value2) {
            addCriterion("OPER_COM_ID between", value1, value2, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdNotBetween(Long value1, Long value2) {
            addCriterion("OPER_COM_ID not between", value1, value2, "operComId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("CREATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("CREATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Long value) {
            addCriterion("CREATE_USER_ID =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Long value) {
            addCriterion("CREATE_USER_ID <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Long value) {
            addCriterion("CREATE_USER_ID >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATE_USER_ID >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Long value) {
            addCriterion("CREATE_USER_ID <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("CREATE_USER_ID <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Long> values) {
            addCriterion("CREATE_USER_ID in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Long> values) {
            addCriterion("CREATE_USER_ID not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Long value1, Long value2) {
            addCriterion("CREATE_USER_ID between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("CREATE_USER_ID not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNull() {
            addCriterion("MODIFY_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNotNull() {
            addCriterion("MODIFY_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdEqualTo(Long value) {
            addCriterion("MODIFY_USER_ID =", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotEqualTo(Long value) {
            addCriterion("MODIFY_USER_ID <>", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThan(Long value) {
            addCriterion("MODIFY_USER_ID >", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("MODIFY_USER_ID >=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThan(Long value) {
            addCriterion("MODIFY_USER_ID <", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThanOrEqualTo(Long value) {
            addCriterion("MODIFY_USER_ID <=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIn(List<Long> values) {
            addCriterion("MODIFY_USER_ID in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotIn(List<Long> values) {
            addCriterion("MODIFY_USER_ID not in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdBetween(Long value1, Long value2) {
            addCriterion("MODIFY_USER_ID between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotBetween(Long value1, Long value2) {
            addCriterion("MODIFY_USER_ID not between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andStandardPremIsNull() {
            addCriterion("STANDARD_PREM is null");
            return (Criteria) this;
        }

        public Criteria andStandardPremIsNotNull() {
            addCriterion("STANDARD_PREM is not null");
            return (Criteria) this;
        }

        public Criteria andStandardPremEqualTo(BigDecimal value) {
            addCriterion("STANDARD_PREM =", value, "standardPrem");
            return (Criteria) this;
        }

        public Criteria andStandardPremNotEqualTo(BigDecimal value) {
            addCriterion("STANDARD_PREM <>", value, "standardPrem");
            return (Criteria) this;
        }

        public Criteria andStandardPremGreaterThan(BigDecimal value) {
            addCriterion("STANDARD_PREM >", value, "standardPrem");
            return (Criteria) this;
        }

        public Criteria andStandardPremGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("STANDARD_PREM >=", value, "standardPrem");
            return (Criteria) this;
        }

        public Criteria andStandardPremLessThan(BigDecimal value) {
            addCriterion("STANDARD_PREM <", value, "standardPrem");
            return (Criteria) this;
        }

        public Criteria andStandardPremLessThanOrEqualTo(BigDecimal value) {
            addCriterion("STANDARD_PREM <=", value, "standardPrem");
            return (Criteria) this;
        }

        public Criteria andStandardPremIn(List<BigDecimal> values) {
            addCriterion("STANDARD_PREM in", values, "standardPrem");
            return (Criteria) this;
        }

        public Criteria andStandardPremNotIn(List<BigDecimal> values) {
            addCriterion("STANDARD_PREM not in", values, "standardPrem");
            return (Criteria) this;
        }

        public Criteria andStandardPremBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STANDARD_PREM between", value1, value2, "standardPrem");
            return (Criteria) this;
        }

        public Criteria andStandardPremNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STANDARD_PREM not between", value1, value2, "standardPrem");
            return (Criteria) this;
        }

        public Criteria andStandardAssetIsNull() {
            addCriterion("STANDARD_ASSET is null");
            return (Criteria) this;
        }

        public Criteria andStandardAssetIsNotNull() {
            addCriterion("STANDARD_ASSET is not null");
            return (Criteria) this;
        }

        public Criteria andStandardAssetEqualTo(BigDecimal value) {
            addCriterion("STANDARD_ASSET =", value, "standardAsset");
            return (Criteria) this;
        }

        public Criteria andStandardAssetNotEqualTo(BigDecimal value) {
            addCriterion("STANDARD_ASSET <>", value, "standardAsset");
            return (Criteria) this;
        }

        public Criteria andStandardAssetGreaterThan(BigDecimal value) {
            addCriterion("STANDARD_ASSET >", value, "standardAsset");
            return (Criteria) this;
        }

        public Criteria andStandardAssetGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("STANDARD_ASSET >=", value, "standardAsset");
            return (Criteria) this;
        }

        public Criteria andStandardAssetLessThan(BigDecimal value) {
            addCriterion("STANDARD_ASSET <", value, "standardAsset");
            return (Criteria) this;
        }

        public Criteria andStandardAssetLessThanOrEqualTo(BigDecimal value) {
            addCriterion("STANDARD_ASSET <=", value, "standardAsset");
            return (Criteria) this;
        }

        public Criteria andStandardAssetIn(List<BigDecimal> values) {
            addCriterion("STANDARD_ASSET in", values, "standardAsset");
            return (Criteria) this;
        }

        public Criteria andStandardAssetNotIn(List<BigDecimal> values) {
            addCriterion("STANDARD_ASSET not in", values, "standardAsset");
            return (Criteria) this;
        }

        public Criteria andStandardAssetBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STANDARD_ASSET between", value1, value2, "standardAsset");
            return (Criteria) this;
        }

        public Criteria andStandardAssetNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STANDARD_ASSET not between", value1, value2, "standardAsset");
            return (Criteria) this;
        }

        public Criteria andSettleStatusIsNull() {
            addCriterion("SETTLE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSettleStatusIsNotNull() {
            addCriterion("SETTLE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSettleStatusEqualTo(String value) {
            addCriterion("SETTLE_STATUS =", value, "settleStatus");
            return (Criteria) this;
        }

        public Criteria andSettleStatusNotEqualTo(String value) {
            addCriterion("SETTLE_STATUS <>", value, "settleStatus");
            return (Criteria) this;
        }

        public Criteria andSettleStatusGreaterThan(String value) {
            addCriterion("SETTLE_STATUS >", value, "settleStatus");
            return (Criteria) this;
        }

        public Criteria andSettleStatusGreaterThanOrEqualTo(String value) {
            addCriterion("SETTLE_STATUS >=", value, "settleStatus");
            return (Criteria) this;
        }

        public Criteria andSettleStatusLessThan(String value) {
            addCriterion("SETTLE_STATUS <", value, "settleStatus");
            return (Criteria) this;
        }

        public Criteria andSettleStatusLessThanOrEqualTo(String value) {
            addCriterion("SETTLE_STATUS <=", value, "settleStatus");
            return (Criteria) this;
        }

        public Criteria andSettleStatusLike(String value) {
            addCriterion("SETTLE_STATUS like", value, "settleStatus");
            return (Criteria) this;
        }

        public Criteria andSettleStatusNotLike(String value) {
            addCriterion("SETTLE_STATUS not like", value, "settleStatus");
            return (Criteria) this;
        }

        public Criteria andSettleStatusIn(List<String> values) {
            addCriterion("SETTLE_STATUS in", values, "settleStatus");
            return (Criteria) this;
        }

        public Criteria andSettleStatusNotIn(List<String> values) {
            addCriterion("SETTLE_STATUS not in", values, "settleStatus");
            return (Criteria) this;
        }

        public Criteria andSettleStatusBetween(String value1, String value2) {
            addCriterion("SETTLE_STATUS between", value1, value2, "settleStatus");
            return (Criteria) this;
        }

        public Criteria andSettleStatusNotBetween(String value1, String value2) {
            addCriterion("SETTLE_STATUS not between", value1, value2, "settleStatus");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdIsNull() {
            addCriterion("DEPARTMENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdIsNotNull() {
            addCriterion("DEPARTMENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdEqualTo(Long value) {
            addCriterion("DEPARTMENT_ID =", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotEqualTo(Long value) {
            addCriterion("DEPARTMENT_ID <>", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdGreaterThan(Long value) {
            addCriterion("DEPARTMENT_ID >", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("DEPARTMENT_ID >=", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdLessThan(Long value) {
            addCriterion("DEPARTMENT_ID <", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdLessThanOrEqualTo(Long value) {
            addCriterion("DEPARTMENT_ID <=", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdIn(List<Long> values) {
            addCriterion("DEPARTMENT_ID in", values, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotIn(List<Long> values) {
            addCriterion("DEPARTMENT_ID not in", values, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdBetween(Long value1, Long value2) {
            addCriterion("DEPARTMENT_ID between", value1, value2, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotBetween(Long value1, Long value2) {
            addCriterion("DEPARTMENT_ID not between", value1, value2, "departmentId");
            return (Criteria) this;
        }

        public Criteria andBonusRateIsNull() {
            addCriterion("BONUS_RATE is null");
            return (Criteria) this;
        }

        public Criteria andBonusRateIsNotNull() {
            addCriterion("BONUS_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andBonusRateEqualTo(BigDecimal value) {
            addCriterion("BONUS_RATE =", value, "bonusRate");
            return (Criteria) this;
        }

        public Criteria andBonusRateNotEqualTo(BigDecimal value) {
            addCriterion("BONUS_RATE <>", value, "bonusRate");
            return (Criteria) this;
        }

        public Criteria andBonusRateGreaterThan(BigDecimal value) {
            addCriterion("BONUS_RATE >", value, "bonusRate");
            return (Criteria) this;
        }

        public Criteria andBonusRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BONUS_RATE >=", value, "bonusRate");
            return (Criteria) this;
        }

        public Criteria andBonusRateLessThan(BigDecimal value) {
            addCriterion("BONUS_RATE <", value, "bonusRate");
            return (Criteria) this;
        }

        public Criteria andBonusRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BONUS_RATE <=", value, "bonusRate");
            return (Criteria) this;
        }

        public Criteria andBonusRateIn(List<BigDecimal> values) {
            addCriterion("BONUS_RATE in", values, "bonusRate");
            return (Criteria) this;
        }

        public Criteria andBonusRateNotIn(List<BigDecimal> values) {
            addCriterion("BONUS_RATE not in", values, "bonusRate");
            return (Criteria) this;
        }

        public Criteria andBonusRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BONUS_RATE between", value1, value2, "bonusRate");
            return (Criteria) this;
        }

        public Criteria andBonusRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BONUS_RATE not between", value1, value2, "bonusRate");
            return (Criteria) this;
        }

        public Criteria andScaleRateIsNull() {
            addCriterion("SCALE_RATE is null");
            return (Criteria) this;
        }

        public Criteria andScaleRateIsNotNull() {
            addCriterion("SCALE_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andScaleRateEqualTo(BigDecimal value) {
            addCriterion("SCALE_RATE =", value, "scaleRate");
            return (Criteria) this;
        }

        public Criteria andScaleRateNotEqualTo(BigDecimal value) {
            addCriterion("SCALE_RATE <>", value, "scaleRate");
            return (Criteria) this;
        }

        public Criteria andScaleRateGreaterThan(BigDecimal value) {
            addCriterion("SCALE_RATE >", value, "scaleRate");
            return (Criteria) this;
        }

        public Criteria andScaleRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SCALE_RATE >=", value, "scaleRate");
            return (Criteria) this;
        }

        public Criteria andScaleRateLessThan(BigDecimal value) {
            addCriterion("SCALE_RATE <", value, "scaleRate");
            return (Criteria) this;
        }

        public Criteria andScaleRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SCALE_RATE <=", value, "scaleRate");
            return (Criteria) this;
        }

        public Criteria andScaleRateIn(List<BigDecimal> values) {
            addCriterion("SCALE_RATE in", values, "scaleRate");
            return (Criteria) this;
        }

        public Criteria andScaleRateNotIn(List<BigDecimal> values) {
            addCriterion("SCALE_RATE not in", values, "scaleRate");
            return (Criteria) this;
        }

        public Criteria andScaleRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SCALE_RATE between", value1, value2, "scaleRate");
            return (Criteria) this;
        }

        public Criteria andScaleRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SCALE_RATE not between", value1, value2, "scaleRate");
            return (Criteria) this;
        }

        public Criteria andWageCountIsNull() {
            addCriterion("WAGE_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andWageCountIsNotNull() {
            addCriterion("WAGE_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andWageCountEqualTo(String value) {
            addCriterion("WAGE_COUNT =", value, "wageCount");
            return (Criteria) this;
        }

        public Criteria andWageCountNotEqualTo(String value) {
            addCriterion("WAGE_COUNT <>", value, "wageCount");
            return (Criteria) this;
        }

        public Criteria andWageCountGreaterThan(String value) {
            addCriterion("WAGE_COUNT >", value, "wageCount");
            return (Criteria) this;
        }

        public Criteria andWageCountGreaterThanOrEqualTo(String value) {
            addCriterion("WAGE_COUNT >=", value, "wageCount");
            return (Criteria) this;
        }

        public Criteria andWageCountLessThan(String value) {
            addCriterion("WAGE_COUNT <", value, "wageCount");
            return (Criteria) this;
        }

        public Criteria andWageCountLessThanOrEqualTo(String value) {
            addCriterion("WAGE_COUNT <=", value, "wageCount");
            return (Criteria) this;
        }

        public Criteria andWageCountLike(String value) {
            addCriterion("WAGE_COUNT like", value, "wageCount");
            return (Criteria) this;
        }

        public Criteria andWageCountNotLike(String value) {
            addCriterion("WAGE_COUNT not like", value, "wageCount");
            return (Criteria) this;
        }

        public Criteria andWageCountIn(List<String> values) {
            addCriterion("WAGE_COUNT in", values, "wageCount");
            return (Criteria) this;
        }

        public Criteria andWageCountNotIn(List<String> values) {
            addCriterion("WAGE_COUNT not in", values, "wageCount");
            return (Criteria) this;
        }

        public Criteria andWageCountBetween(String value1, String value2) {
            addCriterion("WAGE_COUNT between", value1, value2, "wageCount");
            return (Criteria) this;
        }

        public Criteria andWageCountNotBetween(String value1, String value2) {
            addCriterion("WAGE_COUNT not between", value1, value2, "wageCount");
            return (Criteria) this;
        }

        public Criteria andAgentWageInfoIdIsNull() {
            addCriterion("AGENT_WAGE_INFO_ID is null");
            return (Criteria) this;
        }

        public Criteria andAgentWageInfoIdIsNotNull() {
            addCriterion("AGENT_WAGE_INFO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAgentWageInfoIdEqualTo(Long value) {
            addCriterion("AGENT_WAGE_INFO_ID =", value, "agentWageInfoId");
            return (Criteria) this;
        }

        public Criteria andAgentWageInfoIdNotEqualTo(Long value) {
            addCriterion("AGENT_WAGE_INFO_ID <>", value, "agentWageInfoId");
            return (Criteria) this;
        }

        public Criteria andAgentWageInfoIdGreaterThan(Long value) {
            addCriterion("AGENT_WAGE_INFO_ID >", value, "agentWageInfoId");
            return (Criteria) this;
        }

        public Criteria andAgentWageInfoIdGreaterThanOrEqualTo(Long value) {
            addCriterion("AGENT_WAGE_INFO_ID >=", value, "agentWageInfoId");
            return (Criteria) this;
        }

        public Criteria andAgentWageInfoIdLessThan(Long value) {
            addCriterion("AGENT_WAGE_INFO_ID <", value, "agentWageInfoId");
            return (Criteria) this;
        }

        public Criteria andAgentWageInfoIdLessThanOrEqualTo(Long value) {
            addCriterion("AGENT_WAGE_INFO_ID <=", value, "agentWageInfoId");
            return (Criteria) this;
        }

        public Criteria andAgentWageInfoIdIn(List<Long> values) {
            addCriterion("AGENT_WAGE_INFO_ID in", values, "agentWageInfoId");
            return (Criteria) this;
        }

        public Criteria andAgentWageInfoIdNotIn(List<Long> values) {
            addCriterion("AGENT_WAGE_INFO_ID not in", values, "agentWageInfoId");
            return (Criteria) this;
        }

        public Criteria andAgentWageInfoIdBetween(Long value1, Long value2) {
            addCriterion("AGENT_WAGE_INFO_ID between", value1, value2, "agentWageInfoId");
            return (Criteria) this;
        }

        public Criteria andAgentWageInfoIdNotBetween(Long value1, Long value2) {
            addCriterion("AGENT_WAGE_INFO_ID not between", value1, value2, "agentWageInfoId");
            return (Criteria) this;
        }

        public Criteria andSettleDateIsNull() {
            addCriterion("SETTLE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSettleDateIsNotNull() {
            addCriterion("SETTLE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSettleDateEqualTo(Date value) {
            addCriterionForJDBCDate("SETTLE_DATE =", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("SETTLE_DATE <>", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateGreaterThan(Date value) {
            addCriterionForJDBCDate("SETTLE_DATE >", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SETTLE_DATE >=", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateLessThan(Date value) {
            addCriterionForJDBCDate("SETTLE_DATE <", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SETTLE_DATE <=", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateIn(List<Date> values) {
            addCriterionForJDBCDate("SETTLE_DATE in", values, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("SETTLE_DATE not in", values, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SETTLE_DATE between", value1, value2, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SETTLE_DATE not between", value1, value2, "settleDate");
            return (Criteria) this;
        }

        public Criteria andForwardDateIsNull() {
            addCriterion("FORWARD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andForwardDateIsNotNull() {
            addCriterion("FORWARD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andForwardDateEqualTo(Date value) {
            addCriterionForJDBCDate("FORWARD_DATE =", value, "forwardDate");
            return (Criteria) this;
        }

        public Criteria andForwardDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("FORWARD_DATE <>", value, "forwardDate");
            return (Criteria) this;
        }

        public Criteria andForwardDateGreaterThan(Date value) {
            addCriterionForJDBCDate("FORWARD_DATE >", value, "forwardDate");
            return (Criteria) this;
        }

        public Criteria andForwardDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FORWARD_DATE >=", value, "forwardDate");
            return (Criteria) this;
        }

        public Criteria andForwardDateLessThan(Date value) {
            addCriterionForJDBCDate("FORWARD_DATE <", value, "forwardDate");
            return (Criteria) this;
        }

        public Criteria andForwardDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FORWARD_DATE <=", value, "forwardDate");
            return (Criteria) this;
        }

        public Criteria andForwardDateIn(List<Date> values) {
            addCriterionForJDBCDate("FORWARD_DATE in", values, "forwardDate");
            return (Criteria) this;
        }

        public Criteria andForwardDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("FORWARD_DATE not in", values, "forwardDate");
            return (Criteria) this;
        }

        public Criteria andForwardDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FORWARD_DATE between", value1, value2, "forwardDate");
            return (Criteria) this;
        }

        public Criteria andForwardDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FORWARD_DATE not between", value1, value2, "forwardDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_agent_wage
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 16 15:12:22 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_agent_wage
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}