package com.fms.db.model;

import java.util.ArrayList;
import java.util.List;

public class DefAddressExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_def_address
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_def_address
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_def_address
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_def_address
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public DefAddressExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_def_address
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_def_address
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_def_address
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_def_address
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_def_address
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_def_address
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_def_address
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_def_address
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_def_address
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_def_address
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_def_address
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPlaceTypeIsNull() {
            addCriterion("PLACE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPlaceTypeIsNotNull() {
            addCriterion("PLACE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPlaceTypeEqualTo(String value) {
            addCriterion("PLACE_TYPE =", value, "placeType");
            return (Criteria) this;
        }

        public Criteria andPlaceTypeNotEqualTo(String value) {
            addCriterion("PLACE_TYPE <>", value, "placeType");
            return (Criteria) this;
        }

        public Criteria andPlaceTypeGreaterThan(String value) {
            addCriterion("PLACE_TYPE >", value, "placeType");
            return (Criteria) this;
        }

        public Criteria andPlaceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PLACE_TYPE >=", value, "placeType");
            return (Criteria) this;
        }

        public Criteria andPlaceTypeLessThan(String value) {
            addCriterion("PLACE_TYPE <", value, "placeType");
            return (Criteria) this;
        }

        public Criteria andPlaceTypeLessThanOrEqualTo(String value) {
            addCriterion("PLACE_TYPE <=", value, "placeType");
            return (Criteria) this;
        }

        public Criteria andPlaceTypeLike(String value) {
            addCriterion("PLACE_TYPE like", value, "placeType");
            return (Criteria) this;
        }

        public Criteria andPlaceTypeNotLike(String value) {
            addCriterion("PLACE_TYPE not like", value, "placeType");
            return (Criteria) this;
        }

        public Criteria andPlaceTypeIn(List<String> values) {
            addCriterion("PLACE_TYPE in", values, "placeType");
            return (Criteria) this;
        }

        public Criteria andPlaceTypeNotIn(List<String> values) {
            addCriterion("PLACE_TYPE not in", values, "placeType");
            return (Criteria) this;
        }

        public Criteria andPlaceTypeBetween(String value1, String value2) {
            addCriterion("PLACE_TYPE between", value1, value2, "placeType");
            return (Criteria) this;
        }

        public Criteria andPlaceTypeNotBetween(String value1, String value2) {
            addCriterion("PLACE_TYPE not between", value1, value2, "placeType");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeIsNull() {
            addCriterion("PLACE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeIsNotNull() {
            addCriterion("PLACE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeEqualTo(String value) {
            addCriterion("PLACE_CODE =", value, "placeCode");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeNotEqualTo(String value) {
            addCriterion("PLACE_CODE <>", value, "placeCode");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeGreaterThan(String value) {
            addCriterion("PLACE_CODE >", value, "placeCode");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PLACE_CODE >=", value, "placeCode");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeLessThan(String value) {
            addCriterion("PLACE_CODE <", value, "placeCode");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeLessThanOrEqualTo(String value) {
            addCriterion("PLACE_CODE <=", value, "placeCode");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeLike(String value) {
            addCriterion("PLACE_CODE like", value, "placeCode");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeNotLike(String value) {
            addCriterion("PLACE_CODE not like", value, "placeCode");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeIn(List<String> values) {
            addCriterion("PLACE_CODE in", values, "placeCode");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeNotIn(List<String> values) {
            addCriterion("PLACE_CODE not in", values, "placeCode");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeBetween(String value1, String value2) {
            addCriterion("PLACE_CODE between", value1, value2, "placeCode");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeNotBetween(String value1, String value2) {
            addCriterion("PLACE_CODE not between", value1, value2, "placeCode");
            return (Criteria) this;
        }

        public Criteria andPlaceNameIsNull() {
            addCriterion("PLACE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andPlaceNameIsNotNull() {
            addCriterion("PLACE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andPlaceNameEqualTo(String value) {
            addCriterion("PLACE_NAME =", value, "placeName");
            return (Criteria) this;
        }

        public Criteria andPlaceNameNotEqualTo(String value) {
            addCriterion("PLACE_NAME <>", value, "placeName");
            return (Criteria) this;
        }

        public Criteria andPlaceNameGreaterThan(String value) {
            addCriterion("PLACE_NAME >", value, "placeName");
            return (Criteria) this;
        }

        public Criteria andPlaceNameGreaterThanOrEqualTo(String value) {
            addCriterion("PLACE_NAME >=", value, "placeName");
            return (Criteria) this;
        }

        public Criteria andPlaceNameLessThan(String value) {
            addCriterion("PLACE_NAME <", value, "placeName");
            return (Criteria) this;
        }

        public Criteria andPlaceNameLessThanOrEqualTo(String value) {
            addCriterion("PLACE_NAME <=", value, "placeName");
            return (Criteria) this;
        }

        public Criteria andPlaceNameLike(String value) {
            addCriterion("PLACE_NAME like", value, "placeName");
            return (Criteria) this;
        }

        public Criteria andPlaceNameNotLike(String value) {
            addCriterion("PLACE_NAME not like", value, "placeName");
            return (Criteria) this;
        }

        public Criteria andPlaceNameIn(List<String> values) {
            addCriterion("PLACE_NAME in", values, "placeName");
            return (Criteria) this;
        }

        public Criteria andPlaceNameNotIn(List<String> values) {
            addCriterion("PLACE_NAME not in", values, "placeName");
            return (Criteria) this;
        }

        public Criteria andPlaceNameBetween(String value1, String value2) {
            addCriterion("PLACE_NAME between", value1, value2, "placeName");
            return (Criteria) this;
        }

        public Criteria andPlaceNameNotBetween(String value1, String value2) {
            addCriterion("PLACE_NAME not between", value1, value2, "placeName");
            return (Criteria) this;
        }

        public Criteria andUpPlaceCodeIsNull() {
            addCriterion("UP_PLACE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andUpPlaceCodeIsNotNull() {
            addCriterion("UP_PLACE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andUpPlaceCodeEqualTo(String value) {
            addCriterion("UP_PLACE_CODE =", value, "upPlaceCode");
            return (Criteria) this;
        }

        public Criteria andUpPlaceCodeNotEqualTo(String value) {
            addCriterion("UP_PLACE_CODE <>", value, "upPlaceCode");
            return (Criteria) this;
        }

        public Criteria andUpPlaceCodeGreaterThan(String value) {
            addCriterion("UP_PLACE_CODE >", value, "upPlaceCode");
            return (Criteria) this;
        }

        public Criteria andUpPlaceCodeGreaterThanOrEqualTo(String value) {
            addCriterion("UP_PLACE_CODE >=", value, "upPlaceCode");
            return (Criteria) this;
        }

        public Criteria andUpPlaceCodeLessThan(String value) {
            addCriterion("UP_PLACE_CODE <", value, "upPlaceCode");
            return (Criteria) this;
        }

        public Criteria andUpPlaceCodeLessThanOrEqualTo(String value) {
            addCriterion("UP_PLACE_CODE <=", value, "upPlaceCode");
            return (Criteria) this;
        }

        public Criteria andUpPlaceCodeLike(String value) {
            addCriterion("UP_PLACE_CODE like", value, "upPlaceCode");
            return (Criteria) this;
        }

        public Criteria andUpPlaceCodeNotLike(String value) {
            addCriterion("UP_PLACE_CODE not like", value, "upPlaceCode");
            return (Criteria) this;
        }

        public Criteria andUpPlaceCodeIn(List<String> values) {
            addCriterion("UP_PLACE_CODE in", values, "upPlaceCode");
            return (Criteria) this;
        }

        public Criteria andUpPlaceCodeNotIn(List<String> values) {
            addCriterion("UP_PLACE_CODE not in", values, "upPlaceCode");
            return (Criteria) this;
        }

        public Criteria andUpPlaceCodeBetween(String value1, String value2) {
            addCriterion("UP_PLACE_CODE between", value1, value2, "upPlaceCode");
            return (Criteria) this;
        }

        public Criteria andUpPlaceCodeNotBetween(String value1, String value2) {
            addCriterion("UP_PLACE_CODE not between", value1, value2, "upPlaceCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_def_address
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 16 15:12:22 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_def_address
     *
     * @mbggenerated Mon Nov 16 15:12:22 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}