package com.fms.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PDFactorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pd_factor
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pd_factor
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pd_factor
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pd_factor
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public PDFactorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pd_factor
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pd_factor
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pd_factor
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pd_factor
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pd_factor
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pd_factor
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pd_factor
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pd_factor
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pd_factor
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pd_factor
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pd_factor
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPdFactorIdIsNull() {
            addCriterion("PD_FACTOR_ID is null");
            return (Criteria) this;
        }

        public Criteria andPdFactorIdIsNotNull() {
            addCriterion("PD_FACTOR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPdFactorIdEqualTo(Long value) {
            addCriterion("PD_FACTOR_ID =", value, "pdFactorId");
            return (Criteria) this;
        }

        public Criteria andPdFactorIdNotEqualTo(Long value) {
            addCriterion("PD_FACTOR_ID <>", value, "pdFactorId");
            return (Criteria) this;
        }

        public Criteria andPdFactorIdGreaterThan(Long value) {
            addCriterion("PD_FACTOR_ID >", value, "pdFactorId");
            return (Criteria) this;
        }

        public Criteria andPdFactorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PD_FACTOR_ID >=", value, "pdFactorId");
            return (Criteria) this;
        }

        public Criteria andPdFactorIdLessThan(Long value) {
            addCriterion("PD_FACTOR_ID <", value, "pdFactorId");
            return (Criteria) this;
        }

        public Criteria andPdFactorIdLessThanOrEqualTo(Long value) {
            addCriterion("PD_FACTOR_ID <=", value, "pdFactorId");
            return (Criteria) this;
        }

        public Criteria andPdFactorIdIn(List<Long> values) {
            addCriterion("PD_FACTOR_ID in", values, "pdFactorId");
            return (Criteria) this;
        }

        public Criteria andPdFactorIdNotIn(List<Long> values) {
            addCriterion("PD_FACTOR_ID not in", values, "pdFactorId");
            return (Criteria) this;
        }

        public Criteria andPdFactorIdBetween(Long value1, Long value2) {
            addCriterion("PD_FACTOR_ID between", value1, value2, "pdFactorId");
            return (Criteria) this;
        }

        public Criteria andPdFactorIdNotBetween(Long value1, Long value2) {
            addCriterion("PD_FACTOR_ID not between", value1, value2, "pdFactorId");
            return (Criteria) this;
        }

        public Criteria andPdIdIsNull() {
            addCriterion("PD_ID is null");
            return (Criteria) this;
        }

        public Criteria andPdIdIsNotNull() {
            addCriterion("PD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPdIdEqualTo(Long value) {
            addCriterion("PD_ID =", value, "pdId");
            return (Criteria) this;
        }

        public Criteria andPdIdNotEqualTo(Long value) {
            addCriterion("PD_ID <>", value, "pdId");
            return (Criteria) this;
        }

        public Criteria andPdIdGreaterThan(Long value) {
            addCriterion("PD_ID >", value, "pdId");
            return (Criteria) this;
        }

        public Criteria andPdIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PD_ID >=", value, "pdId");
            return (Criteria) this;
        }

        public Criteria andPdIdLessThan(Long value) {
            addCriterion("PD_ID <", value, "pdId");
            return (Criteria) this;
        }

        public Criteria andPdIdLessThanOrEqualTo(Long value) {
            addCriterion("PD_ID <=", value, "pdId");
            return (Criteria) this;
        }

        public Criteria andPdIdIn(List<Long> values) {
            addCriterion("PD_ID in", values, "pdId");
            return (Criteria) this;
        }

        public Criteria andPdIdNotIn(List<Long> values) {
            addCriterion("PD_ID not in", values, "pdId");
            return (Criteria) this;
        }

        public Criteria andPdIdBetween(Long value1, Long value2) {
            addCriterion("PD_ID between", value1, value2, "pdId");
            return (Criteria) this;
        }

        public Criteria andPdIdNotBetween(Long value1, Long value2) {
            addCriterion("PD_ID not between", value1, value2, "pdId");
            return (Criteria) this;
        }

        public Criteria andFactorCodeIsNull() {
            addCriterion("FACTOR_CODE is null");
            return (Criteria) this;
        }

        public Criteria andFactorCodeIsNotNull() {
            addCriterion("FACTOR_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andFactorCodeEqualTo(String value) {
            addCriterion("FACTOR_CODE =", value, "factorCode");
            return (Criteria) this;
        }

        public Criteria andFactorCodeNotEqualTo(String value) {
            addCriterion("FACTOR_CODE <>", value, "factorCode");
            return (Criteria) this;
        }

        public Criteria andFactorCodeGreaterThan(String value) {
            addCriterion("FACTOR_CODE >", value, "factorCode");
            return (Criteria) this;
        }

        public Criteria andFactorCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FACTOR_CODE >=", value, "factorCode");
            return (Criteria) this;
        }

        public Criteria andFactorCodeLessThan(String value) {
            addCriterion("FACTOR_CODE <", value, "factorCode");
            return (Criteria) this;
        }

        public Criteria andFactorCodeLessThanOrEqualTo(String value) {
            addCriterion("FACTOR_CODE <=", value, "factorCode");
            return (Criteria) this;
        }

        public Criteria andFactorCodeLike(String value) {
            addCriterion("FACTOR_CODE like", value, "factorCode");
            return (Criteria) this;
        }

        public Criteria andFactorCodeNotLike(String value) {
            addCriterion("FACTOR_CODE not like", value, "factorCode");
            return (Criteria) this;
        }

        public Criteria andFactorCodeIn(List<String> values) {
            addCriterion("FACTOR_CODE in", values, "factorCode");
            return (Criteria) this;
        }

        public Criteria andFactorCodeNotIn(List<String> values) {
            addCriterion("FACTOR_CODE not in", values, "factorCode");
            return (Criteria) this;
        }

        public Criteria andFactorCodeBetween(String value1, String value2) {
            addCriterion("FACTOR_CODE between", value1, value2, "factorCode");
            return (Criteria) this;
        }

        public Criteria andFactorCodeNotBetween(String value1, String value2) {
            addCriterion("FACTOR_CODE not between", value1, value2, "factorCode");
            return (Criteria) this;
        }

        public Criteria andChooseFlagIsNull() {
            addCriterion("CHOOSE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andChooseFlagIsNotNull() {
            addCriterion("CHOOSE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andChooseFlagEqualTo(String value) {
            addCriterion("CHOOSE_FLAG =", value, "chooseFlag");
            return (Criteria) this;
        }

        public Criteria andChooseFlagNotEqualTo(String value) {
            addCriterion("CHOOSE_FLAG <>", value, "chooseFlag");
            return (Criteria) this;
        }

        public Criteria andChooseFlagGreaterThan(String value) {
            addCriterion("CHOOSE_FLAG >", value, "chooseFlag");
            return (Criteria) this;
        }

        public Criteria andChooseFlagGreaterThanOrEqualTo(String value) {
            addCriterion("CHOOSE_FLAG >=", value, "chooseFlag");
            return (Criteria) this;
        }

        public Criteria andChooseFlagLessThan(String value) {
            addCriterion("CHOOSE_FLAG <", value, "chooseFlag");
            return (Criteria) this;
        }

        public Criteria andChooseFlagLessThanOrEqualTo(String value) {
            addCriterion("CHOOSE_FLAG <=", value, "chooseFlag");
            return (Criteria) this;
        }

        public Criteria andChooseFlagLike(String value) {
            addCriterion("CHOOSE_FLAG like", value, "chooseFlag");
            return (Criteria) this;
        }

        public Criteria andChooseFlagNotLike(String value) {
            addCriterion("CHOOSE_FLAG not like", value, "chooseFlag");
            return (Criteria) this;
        }

        public Criteria andChooseFlagIn(List<String> values) {
            addCriterion("CHOOSE_FLAG in", values, "chooseFlag");
            return (Criteria) this;
        }

        public Criteria andChooseFlagNotIn(List<String> values) {
            addCriterion("CHOOSE_FLAG not in", values, "chooseFlag");
            return (Criteria) this;
        }

        public Criteria andChooseFlagBetween(String value1, String value2) {
            addCriterion("CHOOSE_FLAG between", value1, value2, "chooseFlag");
            return (Criteria) this;
        }

        public Criteria andChooseFlagNotBetween(String value1, String value2) {
            addCriterion("CHOOSE_FLAG not between", value1, value2, "chooseFlag");
            return (Criteria) this;
        }

        public Criteria andFactorTypeIsNull() {
            addCriterion("FACTOR_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andFactorTypeIsNotNull() {
            addCriterion("FACTOR_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andFactorTypeEqualTo(String value) {
            addCriterion("FACTOR_TYPE =", value, "factorType");
            return (Criteria) this;
        }

        public Criteria andFactorTypeNotEqualTo(String value) {
            addCriterion("FACTOR_TYPE <>", value, "factorType");
            return (Criteria) this;
        }

        public Criteria andFactorTypeGreaterThan(String value) {
            addCriterion("FACTOR_TYPE >", value, "factorType");
            return (Criteria) this;
        }

        public Criteria andFactorTypeGreaterThanOrEqualTo(String value) {
            addCriterion("FACTOR_TYPE >=", value, "factorType");
            return (Criteria) this;
        }

        public Criteria andFactorTypeLessThan(String value) {
            addCriterion("FACTOR_TYPE <", value, "factorType");
            return (Criteria) this;
        }

        public Criteria andFactorTypeLessThanOrEqualTo(String value) {
            addCriterion("FACTOR_TYPE <=", value, "factorType");
            return (Criteria) this;
        }

        public Criteria andFactorTypeLike(String value) {
            addCriterion("FACTOR_TYPE like", value, "factorType");
            return (Criteria) this;
        }

        public Criteria andFactorTypeNotLike(String value) {
            addCriterion("FACTOR_TYPE not like", value, "factorType");
            return (Criteria) this;
        }

        public Criteria andFactorTypeIn(List<String> values) {
            addCriterion("FACTOR_TYPE in", values, "factorType");
            return (Criteria) this;
        }

        public Criteria andFactorTypeNotIn(List<String> values) {
            addCriterion("FACTOR_TYPE not in", values, "factorType");
            return (Criteria) this;
        }

        public Criteria andFactorTypeBetween(String value1, String value2) {
            addCriterion("FACTOR_TYPE between", value1, value2, "factorType");
            return (Criteria) this;
        }

        public Criteria andFactorTypeNotBetween(String value1, String value2) {
            addCriterion("FACTOR_TYPE not between", value1, value2, "factorType");
            return (Criteria) this;
        }

        public Criteria andFactorValueIsNull() {
            addCriterion("FACTOR_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andFactorValueIsNotNull() {
            addCriterion("FACTOR_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andFactorValueEqualTo(String value) {
            addCriterion("FACTOR_VALUE =", value, "factorValue");
            return (Criteria) this;
        }

        public Criteria andFactorValueNotEqualTo(String value) {
            addCriterion("FACTOR_VALUE <>", value, "factorValue");
            return (Criteria) this;
        }

        public Criteria andFactorValueGreaterThan(String value) {
            addCriterion("FACTOR_VALUE >", value, "factorValue");
            return (Criteria) this;
        }

        public Criteria andFactorValueGreaterThanOrEqualTo(String value) {
            addCriterion("FACTOR_VALUE >=", value, "factorValue");
            return (Criteria) this;
        }

        public Criteria andFactorValueLessThan(String value) {
            addCriterion("FACTOR_VALUE <", value, "factorValue");
            return (Criteria) this;
        }

        public Criteria andFactorValueLessThanOrEqualTo(String value) {
            addCriterion("FACTOR_VALUE <=", value, "factorValue");
            return (Criteria) this;
        }

        public Criteria andFactorValueLike(String value) {
            addCriterion("FACTOR_VALUE like", value, "factorValue");
            return (Criteria) this;
        }

        public Criteria andFactorValueNotLike(String value) {
            addCriterion("FACTOR_VALUE not like", value, "factorValue");
            return (Criteria) this;
        }

        public Criteria andFactorValueIn(List<String> values) {
            addCriterion("FACTOR_VALUE in", values, "factorValue");
            return (Criteria) this;
        }

        public Criteria andFactorValueNotIn(List<String> values) {
            addCriterion("FACTOR_VALUE not in", values, "factorValue");
            return (Criteria) this;
        }

        public Criteria andFactorValueBetween(String value1, String value2) {
            addCriterion("FACTOR_VALUE between", value1, value2, "factorValue");
            return (Criteria) this;
        }

        public Criteria andFactorValueNotBetween(String value1, String value2) {
            addCriterion("FACTOR_VALUE not between", value1, value2, "factorValue");
            return (Criteria) this;
        }

        public Criteria andRcStateIsNull() {
            addCriterion("RC_STATE is null");
            return (Criteria) this;
        }

        public Criteria andRcStateIsNotNull() {
            addCriterion("RC_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andRcStateEqualTo(String value) {
            addCriterion("RC_STATE =", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateNotEqualTo(String value) {
            addCriterion("RC_STATE <>", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateGreaterThan(String value) {
            addCriterion("RC_STATE >", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateGreaterThanOrEqualTo(String value) {
            addCriterion("RC_STATE >=", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateLessThan(String value) {
            addCriterion("RC_STATE <", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateLessThanOrEqualTo(String value) {
            addCriterion("RC_STATE <=", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateLike(String value) {
            addCriterion("RC_STATE like", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateNotLike(String value) {
            addCriterion("RC_STATE not like", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateIn(List<String> values) {
            addCriterion("RC_STATE in", values, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateNotIn(List<String> values) {
            addCriterion("RC_STATE not in", values, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateBetween(String value1, String value2) {
            addCriterion("RC_STATE between", value1, value2, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateNotBetween(String value1, String value2) {
            addCriterion("RC_STATE not between", value1, value2, "rcState");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("MODIFY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("MODIFY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("MODIFY_DATE =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("MODIFY_DATE <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("MODIFY_DATE >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("MODIFY_DATE <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("MODIFY_DATE in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("MODIFY_DATE not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andOperComIdIsNull() {
            addCriterion("OPER_COM_ID is null");
            return (Criteria) this;
        }

        public Criteria andOperComIdIsNotNull() {
            addCriterion("OPER_COM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOperComIdEqualTo(Long value) {
            addCriterion("OPER_COM_ID =", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdNotEqualTo(Long value) {
            addCriterion("OPER_COM_ID <>", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdGreaterThan(Long value) {
            addCriterion("OPER_COM_ID >", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdGreaterThanOrEqualTo(Long value) {
            addCriterion("OPER_COM_ID >=", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdLessThan(Long value) {
            addCriterion("OPER_COM_ID <", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdLessThanOrEqualTo(Long value) {
            addCriterion("OPER_COM_ID <=", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdIn(List<Long> values) {
            addCriterion("OPER_COM_ID in", values, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdNotIn(List<Long> values) {
            addCriterion("OPER_COM_ID not in", values, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdBetween(Long value1, Long value2) {
            addCriterion("OPER_COM_ID between", value1, value2, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdNotBetween(Long value1, Long value2) {
            addCriterion("OPER_COM_ID not between", value1, value2, "operComId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("CREATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("CREATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Long value) {
            addCriterion("CREATE_USER_ID =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Long value) {
            addCriterion("CREATE_USER_ID <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Long value) {
            addCriterion("CREATE_USER_ID >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATE_USER_ID >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Long value) {
            addCriterion("CREATE_USER_ID <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("CREATE_USER_ID <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Long> values) {
            addCriterion("CREATE_USER_ID in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Long> values) {
            addCriterion("CREATE_USER_ID not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Long value1, Long value2) {
            addCriterion("CREATE_USER_ID between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("CREATE_USER_ID not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNull() {
            addCriterion("MODIFY_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNotNull() {
            addCriterion("MODIFY_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdEqualTo(Long value) {
            addCriterion("MODIFY_USER_ID =", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotEqualTo(Long value) {
            addCriterion("MODIFY_USER_ID <>", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThan(Long value) {
            addCriterion("MODIFY_USER_ID >", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("MODIFY_USER_ID >=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThan(Long value) {
            addCriterion("MODIFY_USER_ID <", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThanOrEqualTo(Long value) {
            addCriterion("MODIFY_USER_ID <=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIn(List<Long> values) {
            addCriterion("MODIFY_USER_ID in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotIn(List<Long> values) {
            addCriterion("MODIFY_USER_ID not in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdBetween(Long value1, Long value2) {
            addCriterion("MODIFY_USER_ID between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotBetween(Long value1, Long value2) {
            addCriterion("MODIFY_USER_ID not between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pd_factor
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 16 15:12:23 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pd_factor
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}