package com.fms.db.model;

import java.util.Date;

public class PRECustomerBaseInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_customer_base_info.PRE_CUST_BASE_INFO_ID
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    private Long preCustBaseInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_customer_base_info.PRE_CUST_NO
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    private String preCustNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_customer_base_info.PRE_CUST_NAME
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    private String preCustName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_customer_base_info.PRE_CUST_SEX
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    private String preCustSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_customer_base_info.PRE_CUST_MOBILE
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    private String preCustMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_customer_base_info.PRE_CUST_TYPE
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    private String preCustType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_customer_base_info.PRE_CUST_RESIDENTIAL_BUILDING
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    private String preCustResidentialBuilding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_customer_base_info.PRE_CUST_BUILDING_NO
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    private String preCustBuildingNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_customer_base_info.PRE_CUST_OBTAIN_WAY
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    private String preCustObtainWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_customer_base_info.PRE_AGENT_ID
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    private Long preAgentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_customer_base_info.RC_STATE
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    private String rcState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_customer_base_info.CREATE_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_customer_base_info.MODIFY_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_customer_base_info.OPER_COM_ID
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    private Long operComId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_customer_base_info.CREATE_USER_ID
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_customer_base_info.MODIFY_USER_ID
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    private Long modifyUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_customer_base_info.PRE_CUST_BASE_INFO_ID
     *
     * @return the value of t_pre_customer_base_info.PRE_CUST_BASE_INFO_ID
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public Long getPreCustBaseInfoId() {
        return preCustBaseInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_customer_base_info.PRE_CUST_BASE_INFO_ID
     *
     * @param preCustBaseInfoId the value for t_pre_customer_base_info.PRE_CUST_BASE_INFO_ID
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setPreCustBaseInfoId(Long preCustBaseInfoId) {
        this.preCustBaseInfoId = preCustBaseInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_customer_base_info.PRE_CUST_NO
     *
     * @return the value of t_pre_customer_base_info.PRE_CUST_NO
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public String getPreCustNo() {
        return preCustNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_customer_base_info.PRE_CUST_NO
     *
     * @param preCustNo the value for t_pre_customer_base_info.PRE_CUST_NO
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setPreCustNo(String preCustNo) {
        this.preCustNo = preCustNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_customer_base_info.PRE_CUST_NAME
     *
     * @return the value of t_pre_customer_base_info.PRE_CUST_NAME
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public String getPreCustName() {
        return preCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_customer_base_info.PRE_CUST_NAME
     *
     * @param preCustName the value for t_pre_customer_base_info.PRE_CUST_NAME
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setPreCustName(String preCustName) {
        this.preCustName = preCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_customer_base_info.PRE_CUST_SEX
     *
     * @return the value of t_pre_customer_base_info.PRE_CUST_SEX
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public String getPreCustSex() {
        return preCustSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_customer_base_info.PRE_CUST_SEX
     *
     * @param preCustSex the value for t_pre_customer_base_info.PRE_CUST_SEX
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setPreCustSex(String preCustSex) {
        this.preCustSex = preCustSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_customer_base_info.PRE_CUST_MOBILE
     *
     * @return the value of t_pre_customer_base_info.PRE_CUST_MOBILE
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public String getPreCustMobile() {
        return preCustMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_customer_base_info.PRE_CUST_MOBILE
     *
     * @param preCustMobile the value for t_pre_customer_base_info.PRE_CUST_MOBILE
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setPreCustMobile(String preCustMobile) {
        this.preCustMobile = preCustMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_customer_base_info.PRE_CUST_TYPE
     *
     * @return the value of t_pre_customer_base_info.PRE_CUST_TYPE
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public String getPreCustType() {
        return preCustType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_customer_base_info.PRE_CUST_TYPE
     *
     * @param preCustType the value for t_pre_customer_base_info.PRE_CUST_TYPE
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setPreCustType(String preCustType) {
        this.preCustType = preCustType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_customer_base_info.PRE_CUST_RESIDENTIAL_BUILDING
     *
     * @return the value of t_pre_customer_base_info.PRE_CUST_RESIDENTIAL_BUILDING
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public String getPreCustResidentialBuilding() {
        return preCustResidentialBuilding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_customer_base_info.PRE_CUST_RESIDENTIAL_BUILDING
     *
     * @param preCustResidentialBuilding the value for t_pre_customer_base_info.PRE_CUST_RESIDENTIAL_BUILDING
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setPreCustResidentialBuilding(String preCustResidentialBuilding) {
        this.preCustResidentialBuilding = preCustResidentialBuilding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_customer_base_info.PRE_CUST_BUILDING_NO
     *
     * @return the value of t_pre_customer_base_info.PRE_CUST_BUILDING_NO
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public String getPreCustBuildingNo() {
        return preCustBuildingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_customer_base_info.PRE_CUST_BUILDING_NO
     *
     * @param preCustBuildingNo the value for t_pre_customer_base_info.PRE_CUST_BUILDING_NO
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setPreCustBuildingNo(String preCustBuildingNo) {
        this.preCustBuildingNo = preCustBuildingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_customer_base_info.PRE_CUST_OBTAIN_WAY
     *
     * @return the value of t_pre_customer_base_info.PRE_CUST_OBTAIN_WAY
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public String getPreCustObtainWay() {
        return preCustObtainWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_customer_base_info.PRE_CUST_OBTAIN_WAY
     *
     * @param preCustObtainWay the value for t_pre_customer_base_info.PRE_CUST_OBTAIN_WAY
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setPreCustObtainWay(String preCustObtainWay) {
        this.preCustObtainWay = preCustObtainWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_customer_base_info.PRE_AGENT_ID
     *
     * @return the value of t_pre_customer_base_info.PRE_AGENT_ID
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public Long getPreAgentId() {
        return preAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_customer_base_info.PRE_AGENT_ID
     *
     * @param preAgentId the value for t_pre_customer_base_info.PRE_AGENT_ID
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setPreAgentId(Long preAgentId) {
        this.preAgentId = preAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_customer_base_info.RC_STATE
     *
     * @return the value of t_pre_customer_base_info.RC_STATE
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public String getRcState() {
        return rcState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_customer_base_info.RC_STATE
     *
     * @param rcState the value for t_pre_customer_base_info.RC_STATE
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setRcState(String rcState) {
        this.rcState = rcState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_customer_base_info.CREATE_DATE
     *
     * @return the value of t_pre_customer_base_info.CREATE_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_customer_base_info.CREATE_DATE
     *
     * @param createDate the value for t_pre_customer_base_info.CREATE_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_customer_base_info.MODIFY_DATE
     *
     * @return the value of t_pre_customer_base_info.MODIFY_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_customer_base_info.MODIFY_DATE
     *
     * @param modifyDate the value for t_pre_customer_base_info.MODIFY_DATE
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_customer_base_info.OPER_COM_ID
     *
     * @return the value of t_pre_customer_base_info.OPER_COM_ID
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public Long getOperComId() {
        return operComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_customer_base_info.OPER_COM_ID
     *
     * @param operComId the value for t_pre_customer_base_info.OPER_COM_ID
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setOperComId(Long operComId) {
        this.operComId = operComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_customer_base_info.CREATE_USER_ID
     *
     * @return the value of t_pre_customer_base_info.CREATE_USER_ID
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_customer_base_info.CREATE_USER_ID
     *
     * @param createUserId the value for t_pre_customer_base_info.CREATE_USER_ID
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_customer_base_info.MODIFY_USER_ID
     *
     * @return the value of t_pre_customer_base_info.MODIFY_USER_ID
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public Long getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_customer_base_info.MODIFY_USER_ID
     *
     * @param modifyUserId the value for t_pre_customer_base_info.MODIFY_USER_ID
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setModifyUserId(Long modifyUserId) {
        this.modifyUserId = modifyUserId;
    }
}