package com.fms.db.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RedemptionInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_redemption_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_redemption_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_redemption_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redemption_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public RedemptionInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redemption_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redemption_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redemption_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redemption_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redemption_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redemption_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redemption_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redemption_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redemption_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_redemption_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_redemption_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andRedemptionInfoIdIsNull() {
            addCriterion("REDEMPTION_INFO_ID is null");
            return (Criteria) this;
        }

        public Criteria andRedemptionInfoIdIsNotNull() {
            addCriterion("REDEMPTION_INFO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRedemptionInfoIdEqualTo(Long value) {
            addCriterion("REDEMPTION_INFO_ID =", value, "redemptionInfoId");
            return (Criteria) this;
        }

        public Criteria andRedemptionInfoIdNotEqualTo(Long value) {
            addCriterion("REDEMPTION_INFO_ID <>", value, "redemptionInfoId");
            return (Criteria) this;
        }

        public Criteria andRedemptionInfoIdGreaterThan(Long value) {
            addCriterion("REDEMPTION_INFO_ID >", value, "redemptionInfoId");
            return (Criteria) this;
        }

        public Criteria andRedemptionInfoIdGreaterThanOrEqualTo(Long value) {
            addCriterion("REDEMPTION_INFO_ID >=", value, "redemptionInfoId");
            return (Criteria) this;
        }

        public Criteria andRedemptionInfoIdLessThan(Long value) {
            addCriterion("REDEMPTION_INFO_ID <", value, "redemptionInfoId");
            return (Criteria) this;
        }

        public Criteria andRedemptionInfoIdLessThanOrEqualTo(Long value) {
            addCriterion("REDEMPTION_INFO_ID <=", value, "redemptionInfoId");
            return (Criteria) this;
        }

        public Criteria andRedemptionInfoIdIn(List<Long> values) {
            addCriterion("REDEMPTION_INFO_ID in", values, "redemptionInfoId");
            return (Criteria) this;
        }

        public Criteria andRedemptionInfoIdNotIn(List<Long> values) {
            addCriterion("REDEMPTION_INFO_ID not in", values, "redemptionInfoId");
            return (Criteria) this;
        }

        public Criteria andRedemptionInfoIdBetween(Long value1, Long value2) {
            addCriterion("REDEMPTION_INFO_ID between", value1, value2, "redemptionInfoId");
            return (Criteria) this;
        }

        public Criteria andRedemptionInfoIdNotBetween(Long value1, Long value2) {
            addCriterion("REDEMPTION_INFO_ID not between", value1, value2, "redemptionInfoId");
            return (Criteria) this;
        }

        public Criteria andPdProductIdIsNull() {
            addCriterion("PD_PRODUCT_ID is null");
            return (Criteria) this;
        }

        public Criteria andPdProductIdIsNotNull() {
            addCriterion("PD_PRODUCT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPdProductIdEqualTo(Long value) {
            addCriterion("PD_PRODUCT_ID =", value, "pdProductId");
            return (Criteria) this;
        }

        public Criteria andPdProductIdNotEqualTo(Long value) {
            addCriterion("PD_PRODUCT_ID <>", value, "pdProductId");
            return (Criteria) this;
        }

        public Criteria andPdProductIdGreaterThan(Long value) {
            addCriterion("PD_PRODUCT_ID >", value, "pdProductId");
            return (Criteria) this;
        }

        public Criteria andPdProductIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PD_PRODUCT_ID >=", value, "pdProductId");
            return (Criteria) this;
        }

        public Criteria andPdProductIdLessThan(Long value) {
            addCriterion("PD_PRODUCT_ID <", value, "pdProductId");
            return (Criteria) this;
        }

        public Criteria andPdProductIdLessThanOrEqualTo(Long value) {
            addCriterion("PD_PRODUCT_ID <=", value, "pdProductId");
            return (Criteria) this;
        }

        public Criteria andPdProductIdIn(List<Long> values) {
            addCriterion("PD_PRODUCT_ID in", values, "pdProductId");
            return (Criteria) this;
        }

        public Criteria andPdProductIdNotIn(List<Long> values) {
            addCriterion("PD_PRODUCT_ID not in", values, "pdProductId");
            return (Criteria) this;
        }

        public Criteria andPdProductIdBetween(Long value1, Long value2) {
            addCriterion("PD_PRODUCT_ID between", value1, value2, "pdProductId");
            return (Criteria) this;
        }

        public Criteria andPdProductIdNotBetween(Long value1, Long value2) {
            addCriterion("PD_PRODUCT_ID not between", value1, value2, "pdProductId");
            return (Criteria) this;
        }

        public Criteria andCustomerNoIsNull() {
            addCriterion("CUSTOMER_NO is null");
            return (Criteria) this;
        }

        public Criteria andCustomerNoIsNotNull() {
            addCriterion("CUSTOMER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerNoEqualTo(String value) {
            addCriterion("CUSTOMER_NO =", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoNotEqualTo(String value) {
            addCriterion("CUSTOMER_NO <>", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoGreaterThan(String value) {
            addCriterion("CUSTOMER_NO >", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTOMER_NO >=", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoLessThan(String value) {
            addCriterion("CUSTOMER_NO <", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoLessThanOrEqualTo(String value) {
            addCriterion("CUSTOMER_NO <=", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoLike(String value) {
            addCriterion("CUSTOMER_NO like", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoNotLike(String value) {
            addCriterion("CUSTOMER_NO not like", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoIn(List<String> values) {
            addCriterion("CUSTOMER_NO in", values, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoNotIn(List<String> values) {
            addCriterion("CUSTOMER_NO not in", values, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoBetween(String value1, String value2) {
            addCriterion("CUSTOMER_NO between", value1, value2, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoNotBetween(String value1, String value2) {
            addCriterion("CUSTOMER_NO not between", value1, value2, "customerNo");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalShareIsNull() {
            addCriterion("REDEMPTION_TOTAL_SHARE is null");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalShareIsNotNull() {
            addCriterion("REDEMPTION_TOTAL_SHARE is not null");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalShareEqualTo(BigDecimal value) {
            addCriterion("REDEMPTION_TOTAL_SHARE =", value, "redemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalShareNotEqualTo(BigDecimal value) {
            addCriterion("REDEMPTION_TOTAL_SHARE <>", value, "redemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalShareGreaterThan(BigDecimal value) {
            addCriterion("REDEMPTION_TOTAL_SHARE >", value, "redemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalShareGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("REDEMPTION_TOTAL_SHARE >=", value, "redemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalShareLessThan(BigDecimal value) {
            addCriterion("REDEMPTION_TOTAL_SHARE <", value, "redemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalShareLessThanOrEqualTo(BigDecimal value) {
            addCriterion("REDEMPTION_TOTAL_SHARE <=", value, "redemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalShareIn(List<BigDecimal> values) {
            addCriterion("REDEMPTION_TOTAL_SHARE in", values, "redemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalShareNotIn(List<BigDecimal> values) {
            addCriterion("REDEMPTION_TOTAL_SHARE not in", values, "redemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalShareBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REDEMPTION_TOTAL_SHARE between", value1, value2, "redemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalShareNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REDEMPTION_TOTAL_SHARE not between", value1, value2, "redemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalMoneyIsNull() {
            addCriterion("REDEMPTION_TOTAL_MONEY is null");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalMoneyIsNotNull() {
            addCriterion("REDEMPTION_TOTAL_MONEY is not null");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalMoneyEqualTo(BigDecimal value) {
            addCriterion("REDEMPTION_TOTAL_MONEY =", value, "redemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalMoneyNotEqualTo(BigDecimal value) {
            addCriterion("REDEMPTION_TOTAL_MONEY <>", value, "redemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalMoneyGreaterThan(BigDecimal value) {
            addCriterion("REDEMPTION_TOTAL_MONEY >", value, "redemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("REDEMPTION_TOTAL_MONEY >=", value, "redemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalMoneyLessThan(BigDecimal value) {
            addCriterion("REDEMPTION_TOTAL_MONEY <", value, "redemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("REDEMPTION_TOTAL_MONEY <=", value, "redemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalMoneyIn(List<BigDecimal> values) {
            addCriterion("REDEMPTION_TOTAL_MONEY in", values, "redemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalMoneyNotIn(List<BigDecimal> values) {
            addCriterion("REDEMPTION_TOTAL_MONEY not in", values, "redemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REDEMPTION_TOTAL_MONEY between", value1, value2, "redemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andRedemptionTotalMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REDEMPTION_TOTAL_MONEY not between", value1, value2, "redemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andReferenceNetValueIsNull() {
            addCriterion("REFERENCE_NET_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andReferenceNetValueIsNotNull() {
            addCriterion("REFERENCE_NET_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andReferenceNetValueEqualTo(BigDecimal value) {
            addCriterion("REFERENCE_NET_VALUE =", value, "referenceNetValue");
            return (Criteria) this;
        }

        public Criteria andReferenceNetValueNotEqualTo(BigDecimal value) {
            addCriterion("REFERENCE_NET_VALUE <>", value, "referenceNetValue");
            return (Criteria) this;
        }

        public Criteria andReferenceNetValueGreaterThan(BigDecimal value) {
            addCriterion("REFERENCE_NET_VALUE >", value, "referenceNetValue");
            return (Criteria) this;
        }

        public Criteria andReferenceNetValueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("REFERENCE_NET_VALUE >=", value, "referenceNetValue");
            return (Criteria) this;
        }

        public Criteria andReferenceNetValueLessThan(BigDecimal value) {
            addCriterion("REFERENCE_NET_VALUE <", value, "referenceNetValue");
            return (Criteria) this;
        }

        public Criteria andReferenceNetValueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("REFERENCE_NET_VALUE <=", value, "referenceNetValue");
            return (Criteria) this;
        }

        public Criteria andReferenceNetValueIn(List<BigDecimal> values) {
            addCriterion("REFERENCE_NET_VALUE in", values, "referenceNetValue");
            return (Criteria) this;
        }

        public Criteria andReferenceNetValueNotIn(List<BigDecimal> values) {
            addCriterion("REFERENCE_NET_VALUE not in", values, "referenceNetValue");
            return (Criteria) this;
        }

        public Criteria andReferenceNetValueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REFERENCE_NET_VALUE between", value1, value2, "referenceNetValue");
            return (Criteria) this;
        }

        public Criteria andReferenceNetValueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REFERENCE_NET_VALUE not between", value1, value2, "referenceNetValue");
            return (Criteria) this;
        }

        public Criteria andRedemptionOpendayIsNull() {
            addCriterion("REDEMPTION_OPENDAY is null");
            return (Criteria) this;
        }

        public Criteria andRedemptionOpendayIsNotNull() {
            addCriterion("REDEMPTION_OPENDAY is not null");
            return (Criteria) this;
        }

        public Criteria andRedemptionOpendayEqualTo(Date value) {
            addCriterionForJDBCDate("REDEMPTION_OPENDAY =", value, "redemptionOpenday");
            return (Criteria) this;
        }

        public Criteria andRedemptionOpendayNotEqualTo(Date value) {
            addCriterionForJDBCDate("REDEMPTION_OPENDAY <>", value, "redemptionOpenday");
            return (Criteria) this;
        }

        public Criteria andRedemptionOpendayGreaterThan(Date value) {
            addCriterionForJDBCDate("REDEMPTION_OPENDAY >", value, "redemptionOpenday");
            return (Criteria) this;
        }

        public Criteria andRedemptionOpendayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("REDEMPTION_OPENDAY >=", value, "redemptionOpenday");
            return (Criteria) this;
        }

        public Criteria andRedemptionOpendayLessThan(Date value) {
            addCriterionForJDBCDate("REDEMPTION_OPENDAY <", value, "redemptionOpenday");
            return (Criteria) this;
        }

        public Criteria andRedemptionOpendayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("REDEMPTION_OPENDAY <=", value, "redemptionOpenday");
            return (Criteria) this;
        }

        public Criteria andRedemptionOpendayIn(List<Date> values) {
            addCriterionForJDBCDate("REDEMPTION_OPENDAY in", values, "redemptionOpenday");
            return (Criteria) this;
        }

        public Criteria andRedemptionOpendayNotIn(List<Date> values) {
            addCriterionForJDBCDate("REDEMPTION_OPENDAY not in", values, "redemptionOpenday");
            return (Criteria) this;
        }

        public Criteria andRedemptionOpendayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("REDEMPTION_OPENDAY between", value1, value2, "redemptionOpenday");
            return (Criteria) this;
        }

        public Criteria andRedemptionOpendayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("REDEMPTION_OPENDAY not between", value1, value2, "redemptionOpenday");
            return (Criteria) this;
        }

        public Criteria andRedemptionApplyDateIsNull() {
            addCriterion("REDEMPTION_APPLY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRedemptionApplyDateIsNotNull() {
            addCriterion("REDEMPTION_APPLY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRedemptionApplyDateEqualTo(Date value) {
            addCriterionForJDBCDate("REDEMPTION_APPLY_DATE =", value, "redemptionApplyDate");
            return (Criteria) this;
        }

        public Criteria andRedemptionApplyDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("REDEMPTION_APPLY_DATE <>", value, "redemptionApplyDate");
            return (Criteria) this;
        }

        public Criteria andRedemptionApplyDateGreaterThan(Date value) {
            addCriterionForJDBCDate("REDEMPTION_APPLY_DATE >", value, "redemptionApplyDate");
            return (Criteria) this;
        }

        public Criteria andRedemptionApplyDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("REDEMPTION_APPLY_DATE >=", value, "redemptionApplyDate");
            return (Criteria) this;
        }

        public Criteria andRedemptionApplyDateLessThan(Date value) {
            addCriterionForJDBCDate("REDEMPTION_APPLY_DATE <", value, "redemptionApplyDate");
            return (Criteria) this;
        }

        public Criteria andRedemptionApplyDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("REDEMPTION_APPLY_DATE <=", value, "redemptionApplyDate");
            return (Criteria) this;
        }

        public Criteria andRedemptionApplyDateIn(List<Date> values) {
            addCriterionForJDBCDate("REDEMPTION_APPLY_DATE in", values, "redemptionApplyDate");
            return (Criteria) this;
        }

        public Criteria andRedemptionApplyDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("REDEMPTION_APPLY_DATE not in", values, "redemptionApplyDate");
            return (Criteria) this;
        }

        public Criteria andRedemptionApplyDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("REDEMPTION_APPLY_DATE between", value1, value2, "redemptionApplyDate");
            return (Criteria) this;
        }

        public Criteria andRedemptionApplyDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("REDEMPTION_APPLY_DATE not between", value1, value2, "redemptionApplyDate");
            return (Criteria) this;
        }

        public Criteria andRedemptionStatusIsNull() {
            addCriterion("REDEMPTION_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andRedemptionStatusIsNotNull() {
            addCriterion("REDEMPTION_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andRedemptionStatusEqualTo(String value) {
            addCriterion("REDEMPTION_STATUS =", value, "redemptionStatus");
            return (Criteria) this;
        }

        public Criteria andRedemptionStatusNotEqualTo(String value) {
            addCriterion("REDEMPTION_STATUS <>", value, "redemptionStatus");
            return (Criteria) this;
        }

        public Criteria andRedemptionStatusGreaterThan(String value) {
            addCriterion("REDEMPTION_STATUS >", value, "redemptionStatus");
            return (Criteria) this;
        }

        public Criteria andRedemptionStatusGreaterThanOrEqualTo(String value) {
            addCriterion("REDEMPTION_STATUS >=", value, "redemptionStatus");
            return (Criteria) this;
        }

        public Criteria andRedemptionStatusLessThan(String value) {
            addCriterion("REDEMPTION_STATUS <", value, "redemptionStatus");
            return (Criteria) this;
        }

        public Criteria andRedemptionStatusLessThanOrEqualTo(String value) {
            addCriterion("REDEMPTION_STATUS <=", value, "redemptionStatus");
            return (Criteria) this;
        }

        public Criteria andRedemptionStatusLike(String value) {
            addCriterion("REDEMPTION_STATUS like", value, "redemptionStatus");
            return (Criteria) this;
        }

        public Criteria andRedemptionStatusNotLike(String value) {
            addCriterion("REDEMPTION_STATUS not like", value, "redemptionStatus");
            return (Criteria) this;
        }

        public Criteria andRedemptionStatusIn(List<String> values) {
            addCriterion("REDEMPTION_STATUS in", values, "redemptionStatus");
            return (Criteria) this;
        }

        public Criteria andRedemptionStatusNotIn(List<String> values) {
            addCriterion("REDEMPTION_STATUS not in", values, "redemptionStatus");
            return (Criteria) this;
        }

        public Criteria andRedemptionStatusBetween(String value1, String value2) {
            addCriterion("REDEMPTION_STATUS between", value1, value2, "redemptionStatus");
            return (Criteria) this;
        }

        public Criteria andRedemptionStatusNotBetween(String value1, String value2) {
            addCriterion("REDEMPTION_STATUS not between", value1, value2, "redemptionStatus");
            return (Criteria) this;
        }

        public Criteria andRedemptionInputOperatorIsNull() {
            addCriterion("REDEMPTION_INPUT_OPERATOR is null");
            return (Criteria) this;
        }

        public Criteria andRedemptionInputOperatorIsNotNull() {
            addCriterion("REDEMPTION_INPUT_OPERATOR is not null");
            return (Criteria) this;
        }

        public Criteria andRedemptionInputOperatorEqualTo(String value) {
            addCriterion("REDEMPTION_INPUT_OPERATOR =", value, "redemptionInputOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionInputOperatorNotEqualTo(String value) {
            addCriterion("REDEMPTION_INPUT_OPERATOR <>", value, "redemptionInputOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionInputOperatorGreaterThan(String value) {
            addCriterion("REDEMPTION_INPUT_OPERATOR >", value, "redemptionInputOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionInputOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("REDEMPTION_INPUT_OPERATOR >=", value, "redemptionInputOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionInputOperatorLessThan(String value) {
            addCriterion("REDEMPTION_INPUT_OPERATOR <", value, "redemptionInputOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionInputOperatorLessThanOrEqualTo(String value) {
            addCriterion("REDEMPTION_INPUT_OPERATOR <=", value, "redemptionInputOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionInputOperatorLike(String value) {
            addCriterion("REDEMPTION_INPUT_OPERATOR like", value, "redemptionInputOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionInputOperatorNotLike(String value) {
            addCriterion("REDEMPTION_INPUT_OPERATOR not like", value, "redemptionInputOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionInputOperatorIn(List<String> values) {
            addCriterion("REDEMPTION_INPUT_OPERATOR in", values, "redemptionInputOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionInputOperatorNotIn(List<String> values) {
            addCriterion("REDEMPTION_INPUT_OPERATOR not in", values, "redemptionInputOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionInputOperatorBetween(String value1, String value2) {
            addCriterion("REDEMPTION_INPUT_OPERATOR between", value1, value2, "redemptionInputOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionInputOperatorNotBetween(String value1, String value2) {
            addCriterion("REDEMPTION_INPUT_OPERATOR not between", value1, value2, "redemptionInputOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionCheckOperatorIsNull() {
            addCriterion("REDEMPTION_CHECK_OPERATOR is null");
            return (Criteria) this;
        }

        public Criteria andRedemptionCheckOperatorIsNotNull() {
            addCriterion("REDEMPTION_CHECK_OPERATOR is not null");
            return (Criteria) this;
        }

        public Criteria andRedemptionCheckOperatorEqualTo(String value) {
            addCriterion("REDEMPTION_CHECK_OPERATOR =", value, "redemptionCheckOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionCheckOperatorNotEqualTo(String value) {
            addCriterion("REDEMPTION_CHECK_OPERATOR <>", value, "redemptionCheckOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionCheckOperatorGreaterThan(String value) {
            addCriterion("REDEMPTION_CHECK_OPERATOR >", value, "redemptionCheckOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionCheckOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("REDEMPTION_CHECK_OPERATOR >=", value, "redemptionCheckOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionCheckOperatorLessThan(String value) {
            addCriterion("REDEMPTION_CHECK_OPERATOR <", value, "redemptionCheckOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionCheckOperatorLessThanOrEqualTo(String value) {
            addCriterion("REDEMPTION_CHECK_OPERATOR <=", value, "redemptionCheckOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionCheckOperatorLike(String value) {
            addCriterion("REDEMPTION_CHECK_OPERATOR like", value, "redemptionCheckOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionCheckOperatorNotLike(String value) {
            addCriterion("REDEMPTION_CHECK_OPERATOR not like", value, "redemptionCheckOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionCheckOperatorIn(List<String> values) {
            addCriterion("REDEMPTION_CHECK_OPERATOR in", values, "redemptionCheckOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionCheckOperatorNotIn(List<String> values) {
            addCriterion("REDEMPTION_CHECK_OPERATOR not in", values, "redemptionCheckOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionCheckOperatorBetween(String value1, String value2) {
            addCriterion("REDEMPTION_CHECK_OPERATOR between", value1, value2, "redemptionCheckOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionCheckOperatorNotBetween(String value1, String value2) {
            addCriterion("REDEMPTION_CHECK_OPERATOR not between", value1, value2, "redemptionCheckOperator");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalShareIsNull() {
            addCriterion("ACTU_REDEMPTION_TOTAL_SHARE is null");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalShareIsNotNull() {
            addCriterion("ACTU_REDEMPTION_TOTAL_SHARE is not null");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalShareEqualTo(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_TOTAL_SHARE =", value, "actuRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalShareNotEqualTo(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_TOTAL_SHARE <>", value, "actuRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalShareGreaterThan(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_TOTAL_SHARE >", value, "actuRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalShareGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_TOTAL_SHARE >=", value, "actuRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalShareLessThan(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_TOTAL_SHARE <", value, "actuRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalShareLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_TOTAL_SHARE <=", value, "actuRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalShareIn(List<BigDecimal> values) {
            addCriterion("ACTU_REDEMPTION_TOTAL_SHARE in", values, "actuRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalShareNotIn(List<BigDecimal> values) {
            addCriterion("ACTU_REDEMPTION_TOTAL_SHARE not in", values, "actuRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalShareBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTU_REDEMPTION_TOTAL_SHARE between", value1, value2, "actuRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalShareNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTU_REDEMPTION_TOTAL_SHARE not between", value1, value2, "actuRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalMoneyIsNull() {
            addCriterion("ACTU_REDEMPTION_TOTAL_MONEY is null");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalMoneyIsNotNull() {
            addCriterion("ACTU_REDEMPTION_TOTAL_MONEY is not null");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalMoneyEqualTo(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_TOTAL_MONEY =", value, "actuRedemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalMoneyNotEqualTo(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_TOTAL_MONEY <>", value, "actuRedemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalMoneyGreaterThan(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_TOTAL_MONEY >", value, "actuRedemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_TOTAL_MONEY >=", value, "actuRedemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalMoneyLessThan(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_TOTAL_MONEY <", value, "actuRedemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_TOTAL_MONEY <=", value, "actuRedemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalMoneyIn(List<BigDecimal> values) {
            addCriterion("ACTU_REDEMPTION_TOTAL_MONEY in", values, "actuRedemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalMoneyNotIn(List<BigDecimal> values) {
            addCriterion("ACTU_REDEMPTION_TOTAL_MONEY not in", values, "actuRedemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTU_REDEMPTION_TOTAL_MONEY between", value1, value2, "actuRedemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionTotalMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTU_REDEMPTION_TOTAL_MONEY not between", value1, value2, "actuRedemptionTotalMoney");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionNetValueIsNull() {
            addCriterion("ACTU_REDEMPTION_NET_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionNetValueIsNotNull() {
            addCriterion("ACTU_REDEMPTION_NET_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionNetValueEqualTo(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_NET_VALUE =", value, "actuRedemptionNetValue");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionNetValueNotEqualTo(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_NET_VALUE <>", value, "actuRedemptionNetValue");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionNetValueGreaterThan(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_NET_VALUE >", value, "actuRedemptionNetValue");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionNetValueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_NET_VALUE >=", value, "actuRedemptionNetValue");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionNetValueLessThan(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_NET_VALUE <", value, "actuRedemptionNetValue");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionNetValueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTU_REDEMPTION_NET_VALUE <=", value, "actuRedemptionNetValue");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionNetValueIn(List<BigDecimal> values) {
            addCriterion("ACTU_REDEMPTION_NET_VALUE in", values, "actuRedemptionNetValue");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionNetValueNotIn(List<BigDecimal> values) {
            addCriterion("ACTU_REDEMPTION_NET_VALUE not in", values, "actuRedemptionNetValue");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionNetValueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTU_REDEMPTION_NET_VALUE between", value1, value2, "actuRedemptionNetValue");
            return (Criteria) this;
        }

        public Criteria andActuRedemptionNetValueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTU_REDEMPTION_NET_VALUE not between", value1, value2, "actuRedemptionNetValue");
            return (Criteria) this;
        }

        public Criteria andSubscribeTotalShareIsNull() {
            addCriterion("SUBSCRIBE_TOTAL_SHARE is null");
            return (Criteria) this;
        }

        public Criteria andSubscribeTotalShareIsNotNull() {
            addCriterion("SUBSCRIBE_TOTAL_SHARE is not null");
            return (Criteria) this;
        }

        public Criteria andSubscribeTotalShareEqualTo(BigDecimal value) {
            addCriterion("SUBSCRIBE_TOTAL_SHARE =", value, "subscribeTotalShare");
            return (Criteria) this;
        }

        public Criteria andSubscribeTotalShareNotEqualTo(BigDecimal value) {
            addCriterion("SUBSCRIBE_TOTAL_SHARE <>", value, "subscribeTotalShare");
            return (Criteria) this;
        }

        public Criteria andSubscribeTotalShareGreaterThan(BigDecimal value) {
            addCriterion("SUBSCRIBE_TOTAL_SHARE >", value, "subscribeTotalShare");
            return (Criteria) this;
        }

        public Criteria andSubscribeTotalShareGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUBSCRIBE_TOTAL_SHARE >=", value, "subscribeTotalShare");
            return (Criteria) this;
        }

        public Criteria andSubscribeTotalShareLessThan(BigDecimal value) {
            addCriterion("SUBSCRIBE_TOTAL_SHARE <", value, "subscribeTotalShare");
            return (Criteria) this;
        }

        public Criteria andSubscribeTotalShareLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUBSCRIBE_TOTAL_SHARE <=", value, "subscribeTotalShare");
            return (Criteria) this;
        }

        public Criteria andSubscribeTotalShareIn(List<BigDecimal> values) {
            addCriterion("SUBSCRIBE_TOTAL_SHARE in", values, "subscribeTotalShare");
            return (Criteria) this;
        }

        public Criteria andSubscribeTotalShareNotIn(List<BigDecimal> values) {
            addCriterion("SUBSCRIBE_TOTAL_SHARE not in", values, "subscribeTotalShare");
            return (Criteria) this;
        }

        public Criteria andSubscribeTotalShareBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUBSCRIBE_TOTAL_SHARE between", value1, value2, "subscribeTotalShare");
            return (Criteria) this;
        }

        public Criteria andSubscribeTotalShareNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUBSCRIBE_TOTAL_SHARE not between", value1, value2, "subscribeTotalShare");
            return (Criteria) this;
        }

        public Criteria andAlreadyRedemptionTotalShareIsNull() {
            addCriterion("ALREADY_REDEMPTION_TOTAL_SHARE is null");
            return (Criteria) this;
        }

        public Criteria andAlreadyRedemptionTotalShareIsNotNull() {
            addCriterion("ALREADY_REDEMPTION_TOTAL_SHARE is not null");
            return (Criteria) this;
        }

        public Criteria andAlreadyRedemptionTotalShareEqualTo(BigDecimal value) {
            addCriterion("ALREADY_REDEMPTION_TOTAL_SHARE =", value, "alreadyRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andAlreadyRedemptionTotalShareNotEqualTo(BigDecimal value) {
            addCriterion("ALREADY_REDEMPTION_TOTAL_SHARE <>", value, "alreadyRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andAlreadyRedemptionTotalShareGreaterThan(BigDecimal value) {
            addCriterion("ALREADY_REDEMPTION_TOTAL_SHARE >", value, "alreadyRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andAlreadyRedemptionTotalShareGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ALREADY_REDEMPTION_TOTAL_SHARE >=", value, "alreadyRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andAlreadyRedemptionTotalShareLessThan(BigDecimal value) {
            addCriterion("ALREADY_REDEMPTION_TOTAL_SHARE <", value, "alreadyRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andAlreadyRedemptionTotalShareLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ALREADY_REDEMPTION_TOTAL_SHARE <=", value, "alreadyRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andAlreadyRedemptionTotalShareIn(List<BigDecimal> values) {
            addCriterion("ALREADY_REDEMPTION_TOTAL_SHARE in", values, "alreadyRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andAlreadyRedemptionTotalShareNotIn(List<BigDecimal> values) {
            addCriterion("ALREADY_REDEMPTION_TOTAL_SHARE not in", values, "alreadyRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andAlreadyRedemptionTotalShareBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ALREADY_REDEMPTION_TOTAL_SHARE between", value1, value2, "alreadyRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andAlreadyRedemptionTotalShareNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ALREADY_REDEMPTION_TOTAL_SHARE not between", value1, value2, "alreadyRedemptionTotalShare");
            return (Criteria) this;
        }

        public Criteria andRemainingTotalShareIsNull() {
            addCriterion("REMAINING_TOTAL_SHARE is null");
            return (Criteria) this;
        }

        public Criteria andRemainingTotalShareIsNotNull() {
            addCriterion("REMAINING_TOTAL_SHARE is not null");
            return (Criteria) this;
        }

        public Criteria andRemainingTotalShareEqualTo(BigDecimal value) {
            addCriterion("REMAINING_TOTAL_SHARE =", value, "remainingTotalShare");
            return (Criteria) this;
        }

        public Criteria andRemainingTotalShareNotEqualTo(BigDecimal value) {
            addCriterion("REMAINING_TOTAL_SHARE <>", value, "remainingTotalShare");
            return (Criteria) this;
        }

        public Criteria andRemainingTotalShareGreaterThan(BigDecimal value) {
            addCriterion("REMAINING_TOTAL_SHARE >", value, "remainingTotalShare");
            return (Criteria) this;
        }

        public Criteria andRemainingTotalShareGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("REMAINING_TOTAL_SHARE >=", value, "remainingTotalShare");
            return (Criteria) this;
        }

        public Criteria andRemainingTotalShareLessThan(BigDecimal value) {
            addCriterion("REMAINING_TOTAL_SHARE <", value, "remainingTotalShare");
            return (Criteria) this;
        }

        public Criteria andRemainingTotalShareLessThanOrEqualTo(BigDecimal value) {
            addCriterion("REMAINING_TOTAL_SHARE <=", value, "remainingTotalShare");
            return (Criteria) this;
        }

        public Criteria andRemainingTotalShareIn(List<BigDecimal> values) {
            addCriterion("REMAINING_TOTAL_SHARE in", values, "remainingTotalShare");
            return (Criteria) this;
        }

        public Criteria andRemainingTotalShareNotIn(List<BigDecimal> values) {
            addCriterion("REMAINING_TOTAL_SHARE not in", values, "remainingTotalShare");
            return (Criteria) this;
        }

        public Criteria andRemainingTotalShareBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REMAINING_TOTAL_SHARE between", value1, value2, "remainingTotalShare");
            return (Criteria) this;
        }

        public Criteria andRemainingTotalShareNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REMAINING_TOTAL_SHARE not between", value1, value2, "remainingTotalShare");
            return (Criteria) this;
        }

        public Criteria andRcStateIsNull() {
            addCriterion("RC_STATE is null");
            return (Criteria) this;
        }

        public Criteria andRcStateIsNotNull() {
            addCriterion("RC_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andRcStateEqualTo(String value) {
            addCriterion("RC_STATE =", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateNotEqualTo(String value) {
            addCriterion("RC_STATE <>", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateGreaterThan(String value) {
            addCriterion("RC_STATE >", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateGreaterThanOrEqualTo(String value) {
            addCriterion("RC_STATE >=", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateLessThan(String value) {
            addCriterion("RC_STATE <", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateLessThanOrEqualTo(String value) {
            addCriterion("RC_STATE <=", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateLike(String value) {
            addCriterion("RC_STATE like", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateNotLike(String value) {
            addCriterion("RC_STATE not like", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateIn(List<String> values) {
            addCriterion("RC_STATE in", values, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateNotIn(List<String> values) {
            addCriterion("RC_STATE not in", values, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateBetween(String value1, String value2) {
            addCriterion("RC_STATE between", value1, value2, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateNotBetween(String value1, String value2) {
            addCriterion("RC_STATE not between", value1, value2, "rcState");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("MODIFY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("MODIFY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("MODIFY_DATE =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("MODIFY_DATE <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("MODIFY_DATE >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("MODIFY_DATE <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("MODIFY_DATE in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("MODIFY_DATE not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andOperComIdIsNull() {
            addCriterion("OPER_COM_ID is null");
            return (Criteria) this;
        }

        public Criteria andOperComIdIsNotNull() {
            addCriterion("OPER_COM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOperComIdEqualTo(Long value) {
            addCriterion("OPER_COM_ID =", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdNotEqualTo(Long value) {
            addCriterion("OPER_COM_ID <>", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdGreaterThan(Long value) {
            addCriterion("OPER_COM_ID >", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdGreaterThanOrEqualTo(Long value) {
            addCriterion("OPER_COM_ID >=", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdLessThan(Long value) {
            addCriterion("OPER_COM_ID <", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdLessThanOrEqualTo(Long value) {
            addCriterion("OPER_COM_ID <=", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdIn(List<Long> values) {
            addCriterion("OPER_COM_ID in", values, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdNotIn(List<Long> values) {
            addCriterion("OPER_COM_ID not in", values, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdBetween(Long value1, Long value2) {
            addCriterion("OPER_COM_ID between", value1, value2, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdNotBetween(Long value1, Long value2) {
            addCriterion("OPER_COM_ID not between", value1, value2, "operComId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("CREATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("CREATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Long value) {
            addCriterion("CREATE_USER_ID =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Long value) {
            addCriterion("CREATE_USER_ID <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Long value) {
            addCriterion("CREATE_USER_ID >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATE_USER_ID >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Long value) {
            addCriterion("CREATE_USER_ID <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("CREATE_USER_ID <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Long> values) {
            addCriterion("CREATE_USER_ID in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Long> values) {
            addCriterion("CREATE_USER_ID not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Long value1, Long value2) {
            addCriterion("CREATE_USER_ID between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("CREATE_USER_ID not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNull() {
            addCriterion("MODIFY_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNotNull() {
            addCriterion("MODIFY_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdEqualTo(Long value) {
            addCriterion("MODIFY_USER_ID =", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotEqualTo(Long value) {
            addCriterion("MODIFY_USER_ID <>", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThan(Long value) {
            addCriterion("MODIFY_USER_ID >", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("MODIFY_USER_ID >=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThan(Long value) {
            addCriterion("MODIFY_USER_ID <", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThanOrEqualTo(Long value) {
            addCriterion("MODIFY_USER_ID <=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIn(List<Long> values) {
            addCriterion("MODIFY_USER_ID in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotIn(List<Long> values) {
            addCriterion("MODIFY_USER_ID not in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdBetween(Long value1, Long value2) {
            addCriterion("MODIFY_USER_ID between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotBetween(Long value1, Long value2) {
            addCriterion("MODIFY_USER_ID not between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andRedemptionUploadOperatorIsNull() {
            addCriterion("REDEMPTION_UPLOAD_OPERATOR is null");
            return (Criteria) this;
        }

        public Criteria andRedemptionUploadOperatorIsNotNull() {
            addCriterion("REDEMPTION_UPLOAD_OPERATOR is not null");
            return (Criteria) this;
        }

        public Criteria andRedemptionUploadOperatorEqualTo(String value) {
            addCriterion("REDEMPTION_UPLOAD_OPERATOR =", value, "redemptionUploadOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionUploadOperatorNotEqualTo(String value) {
            addCriterion("REDEMPTION_UPLOAD_OPERATOR <>", value, "redemptionUploadOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionUploadOperatorGreaterThan(String value) {
            addCriterion("REDEMPTION_UPLOAD_OPERATOR >", value, "redemptionUploadOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionUploadOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("REDEMPTION_UPLOAD_OPERATOR >=", value, "redemptionUploadOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionUploadOperatorLessThan(String value) {
            addCriterion("REDEMPTION_UPLOAD_OPERATOR <", value, "redemptionUploadOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionUploadOperatorLessThanOrEqualTo(String value) {
            addCriterion("REDEMPTION_UPLOAD_OPERATOR <=", value, "redemptionUploadOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionUploadOperatorLike(String value) {
            addCriterion("REDEMPTION_UPLOAD_OPERATOR like", value, "redemptionUploadOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionUploadOperatorNotLike(String value) {
            addCriterion("REDEMPTION_UPLOAD_OPERATOR not like", value, "redemptionUploadOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionUploadOperatorIn(List<String> values) {
            addCriterion("REDEMPTION_UPLOAD_OPERATOR in", values, "redemptionUploadOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionUploadOperatorNotIn(List<String> values) {
            addCriterion("REDEMPTION_UPLOAD_OPERATOR not in", values, "redemptionUploadOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionUploadOperatorBetween(String value1, String value2) {
            addCriterion("REDEMPTION_UPLOAD_OPERATOR between", value1, value2, "redemptionUploadOperator");
            return (Criteria) this;
        }

        public Criteria andRedemptionUploadOperatorNotBetween(String value1, String value2) {
            addCriterion("REDEMPTION_UPLOAD_OPERATOR not between", value1, value2, "redemptionUploadOperator");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_redemption_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 16 15:12:23 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_redemption_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}