package com.fms.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysSmsInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public SysSmsInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSysSmsInfoIdIsNull() {
            addCriterion("SYS_SMS_INFO_ID is null");
            return (Criteria) this;
        }

        public Criteria andSysSmsInfoIdIsNotNull() {
            addCriterion("SYS_SMS_INFO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSysSmsInfoIdEqualTo(Long value) {
            addCriterion("SYS_SMS_INFO_ID =", value, "sysSmsInfoId");
            return (Criteria) this;
        }

        public Criteria andSysSmsInfoIdNotEqualTo(Long value) {
            addCriterion("SYS_SMS_INFO_ID <>", value, "sysSmsInfoId");
            return (Criteria) this;
        }

        public Criteria andSysSmsInfoIdGreaterThan(Long value) {
            addCriterion("SYS_SMS_INFO_ID >", value, "sysSmsInfoId");
            return (Criteria) this;
        }

        public Criteria andSysSmsInfoIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SYS_SMS_INFO_ID >=", value, "sysSmsInfoId");
            return (Criteria) this;
        }

        public Criteria andSysSmsInfoIdLessThan(Long value) {
            addCriterion("SYS_SMS_INFO_ID <", value, "sysSmsInfoId");
            return (Criteria) this;
        }

        public Criteria andSysSmsInfoIdLessThanOrEqualTo(Long value) {
            addCriterion("SYS_SMS_INFO_ID <=", value, "sysSmsInfoId");
            return (Criteria) this;
        }

        public Criteria andSysSmsInfoIdIn(List<Long> values) {
            addCriterion("SYS_SMS_INFO_ID in", values, "sysSmsInfoId");
            return (Criteria) this;
        }

        public Criteria andSysSmsInfoIdNotIn(List<Long> values) {
            addCriterion("SYS_SMS_INFO_ID not in", values, "sysSmsInfoId");
            return (Criteria) this;
        }

        public Criteria andSysSmsInfoIdBetween(Long value1, Long value2) {
            addCriterion("SYS_SMS_INFO_ID between", value1, value2, "sysSmsInfoId");
            return (Criteria) this;
        }

        public Criteria andSysSmsInfoIdNotBetween(Long value1, Long value2) {
            addCriterion("SYS_SMS_INFO_ID not between", value1, value2, "sysSmsInfoId");
            return (Criteria) this;
        }

        public Criteria andSysSmsBatchIdIsNull() {
            addCriterion("SYS_SMS_BATCH_ID is null");
            return (Criteria) this;
        }

        public Criteria andSysSmsBatchIdIsNotNull() {
            addCriterion("SYS_SMS_BATCH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSysSmsBatchIdEqualTo(Long value) {
            addCriterion("SYS_SMS_BATCH_ID =", value, "sysSmsBatchId");
            return (Criteria) this;
        }

        public Criteria andSysSmsBatchIdNotEqualTo(Long value) {
            addCriterion("SYS_SMS_BATCH_ID <>", value, "sysSmsBatchId");
            return (Criteria) this;
        }

        public Criteria andSysSmsBatchIdGreaterThan(Long value) {
            addCriterion("SYS_SMS_BATCH_ID >", value, "sysSmsBatchId");
            return (Criteria) this;
        }

        public Criteria andSysSmsBatchIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SYS_SMS_BATCH_ID >=", value, "sysSmsBatchId");
            return (Criteria) this;
        }

        public Criteria andSysSmsBatchIdLessThan(Long value) {
            addCriterion("SYS_SMS_BATCH_ID <", value, "sysSmsBatchId");
            return (Criteria) this;
        }

        public Criteria andSysSmsBatchIdLessThanOrEqualTo(Long value) {
            addCriterion("SYS_SMS_BATCH_ID <=", value, "sysSmsBatchId");
            return (Criteria) this;
        }

        public Criteria andSysSmsBatchIdIn(List<Long> values) {
            addCriterion("SYS_SMS_BATCH_ID in", values, "sysSmsBatchId");
            return (Criteria) this;
        }

        public Criteria andSysSmsBatchIdNotIn(List<Long> values) {
            addCriterion("SYS_SMS_BATCH_ID not in", values, "sysSmsBatchId");
            return (Criteria) this;
        }

        public Criteria andSysSmsBatchIdBetween(Long value1, Long value2) {
            addCriterion("SYS_SMS_BATCH_ID between", value1, value2, "sysSmsBatchId");
            return (Criteria) this;
        }

        public Criteria andSysSmsBatchIdNotBetween(Long value1, Long value2) {
            addCriterion("SYS_SMS_BATCH_ID not between", value1, value2, "sysSmsBatchId");
            return (Criteria) this;
        }

        public Criteria andBusinessNoIsNull() {
            addCriterion("BUSINESS_NO is null");
            return (Criteria) this;
        }

        public Criteria andBusinessNoIsNotNull() {
            addCriterion("BUSINESS_NO is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessNoEqualTo(Long value) {
            addCriterion("BUSINESS_NO =", value, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoNotEqualTo(Long value) {
            addCriterion("BUSINESS_NO <>", value, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoGreaterThan(Long value) {
            addCriterion("BUSINESS_NO >", value, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoGreaterThanOrEqualTo(Long value) {
            addCriterion("BUSINESS_NO >=", value, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoLessThan(Long value) {
            addCriterion("BUSINESS_NO <", value, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoLessThanOrEqualTo(Long value) {
            addCriterion("BUSINESS_NO <=", value, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoIn(List<Long> values) {
            addCriterion("BUSINESS_NO in", values, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoNotIn(List<Long> values) {
            addCriterion("BUSINESS_NO not in", values, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoBetween(Long value1, Long value2) {
            addCriterion("BUSINESS_NO between", value1, value2, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessNoNotBetween(Long value1, Long value2) {
            addCriterion("BUSINESS_NO not between", value1, value2, "businessNo");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIsNull() {
            addCriterion("BUSINESS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIsNotNull() {
            addCriterion("BUSINESS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeEqualTo(String value) {
            addCriterion("BUSINESS_TYPE =", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotEqualTo(String value) {
            addCriterion("BUSINESS_TYPE <>", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeGreaterThan(String value) {
            addCriterion("BUSINESS_TYPE >", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_TYPE >=", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLessThan(String value) {
            addCriterion("BUSINESS_TYPE <", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_TYPE <=", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLike(String value) {
            addCriterion("BUSINESS_TYPE like", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotLike(String value) {
            addCriterion("BUSINESS_TYPE not like", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIn(List<String> values) {
            addCriterion("BUSINESS_TYPE in", values, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotIn(List<String> values) {
            addCriterion("BUSINESS_TYPE not in", values, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeBetween(String value1, String value2) {
            addCriterion("BUSINESS_TYPE between", value1, value2, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotBetween(String value1, String value2) {
            addCriterion("BUSINESS_TYPE not between", value1, value2, "businessType");
            return (Criteria) this;
        }

        public Criteria andSendObjIsNull() {
            addCriterion("SEND_OBJ is null");
            return (Criteria) this;
        }

        public Criteria andSendObjIsNotNull() {
            addCriterion("SEND_OBJ is not null");
            return (Criteria) this;
        }

        public Criteria andSendObjEqualTo(Long value) {
            addCriterion("SEND_OBJ =", value, "sendObj");
            return (Criteria) this;
        }

        public Criteria andSendObjNotEqualTo(Long value) {
            addCriterion("SEND_OBJ <>", value, "sendObj");
            return (Criteria) this;
        }

        public Criteria andSendObjGreaterThan(Long value) {
            addCriterion("SEND_OBJ >", value, "sendObj");
            return (Criteria) this;
        }

        public Criteria andSendObjGreaterThanOrEqualTo(Long value) {
            addCriterion("SEND_OBJ >=", value, "sendObj");
            return (Criteria) this;
        }

        public Criteria andSendObjLessThan(Long value) {
            addCriterion("SEND_OBJ <", value, "sendObj");
            return (Criteria) this;
        }

        public Criteria andSendObjLessThanOrEqualTo(Long value) {
            addCriterion("SEND_OBJ <=", value, "sendObj");
            return (Criteria) this;
        }

        public Criteria andSendObjIn(List<Long> values) {
            addCriterion("SEND_OBJ in", values, "sendObj");
            return (Criteria) this;
        }

        public Criteria andSendObjNotIn(List<Long> values) {
            addCriterion("SEND_OBJ not in", values, "sendObj");
            return (Criteria) this;
        }

        public Criteria andSendObjBetween(Long value1, Long value2) {
            addCriterion("SEND_OBJ between", value1, value2, "sendObj");
            return (Criteria) this;
        }

        public Criteria andSendObjNotBetween(Long value1, Long value2) {
            addCriterion("SEND_OBJ not between", value1, value2, "sendObj");
            return (Criteria) this;
        }

        public Criteria andSendObjNameIsNull() {
            addCriterion("SEND_OBJ_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSendObjNameIsNotNull() {
            addCriterion("SEND_OBJ_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSendObjNameEqualTo(String value) {
            addCriterion("SEND_OBJ_NAME =", value, "sendObjName");
            return (Criteria) this;
        }

        public Criteria andSendObjNameNotEqualTo(String value) {
            addCriterion("SEND_OBJ_NAME <>", value, "sendObjName");
            return (Criteria) this;
        }

        public Criteria andSendObjNameGreaterThan(String value) {
            addCriterion("SEND_OBJ_NAME >", value, "sendObjName");
            return (Criteria) this;
        }

        public Criteria andSendObjNameGreaterThanOrEqualTo(String value) {
            addCriterion("SEND_OBJ_NAME >=", value, "sendObjName");
            return (Criteria) this;
        }

        public Criteria andSendObjNameLessThan(String value) {
            addCriterion("SEND_OBJ_NAME <", value, "sendObjName");
            return (Criteria) this;
        }

        public Criteria andSendObjNameLessThanOrEqualTo(String value) {
            addCriterion("SEND_OBJ_NAME <=", value, "sendObjName");
            return (Criteria) this;
        }

        public Criteria andSendObjNameLike(String value) {
            addCriterion("SEND_OBJ_NAME like", value, "sendObjName");
            return (Criteria) this;
        }

        public Criteria andSendObjNameNotLike(String value) {
            addCriterion("SEND_OBJ_NAME not like", value, "sendObjName");
            return (Criteria) this;
        }

        public Criteria andSendObjNameIn(List<String> values) {
            addCriterion("SEND_OBJ_NAME in", values, "sendObjName");
            return (Criteria) this;
        }

        public Criteria andSendObjNameNotIn(List<String> values) {
            addCriterion("SEND_OBJ_NAME not in", values, "sendObjName");
            return (Criteria) this;
        }

        public Criteria andSendObjNameBetween(String value1, String value2) {
            addCriterion("SEND_OBJ_NAME between", value1, value2, "sendObjName");
            return (Criteria) this;
        }

        public Criteria andSendObjNameNotBetween(String value1, String value2) {
            addCriterion("SEND_OBJ_NAME not between", value1, value2, "sendObjName");
            return (Criteria) this;
        }

        public Criteria andSendObjTypeIsNull() {
            addCriterion("SEND_OBJ_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSendObjTypeIsNotNull() {
            addCriterion("SEND_OBJ_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSendObjTypeEqualTo(String value) {
            addCriterion("SEND_OBJ_TYPE =", value, "sendObjType");
            return (Criteria) this;
        }

        public Criteria andSendObjTypeNotEqualTo(String value) {
            addCriterion("SEND_OBJ_TYPE <>", value, "sendObjType");
            return (Criteria) this;
        }

        public Criteria andSendObjTypeGreaterThan(String value) {
            addCriterion("SEND_OBJ_TYPE >", value, "sendObjType");
            return (Criteria) this;
        }

        public Criteria andSendObjTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SEND_OBJ_TYPE >=", value, "sendObjType");
            return (Criteria) this;
        }

        public Criteria andSendObjTypeLessThan(String value) {
            addCriterion("SEND_OBJ_TYPE <", value, "sendObjType");
            return (Criteria) this;
        }

        public Criteria andSendObjTypeLessThanOrEqualTo(String value) {
            addCriterion("SEND_OBJ_TYPE <=", value, "sendObjType");
            return (Criteria) this;
        }

        public Criteria andSendObjTypeLike(String value) {
            addCriterion("SEND_OBJ_TYPE like", value, "sendObjType");
            return (Criteria) this;
        }

        public Criteria andSendObjTypeNotLike(String value) {
            addCriterion("SEND_OBJ_TYPE not like", value, "sendObjType");
            return (Criteria) this;
        }

        public Criteria andSendObjTypeIn(List<String> values) {
            addCriterion("SEND_OBJ_TYPE in", values, "sendObjType");
            return (Criteria) this;
        }

        public Criteria andSendObjTypeNotIn(List<String> values) {
            addCriterion("SEND_OBJ_TYPE not in", values, "sendObjType");
            return (Criteria) this;
        }

        public Criteria andSendObjTypeBetween(String value1, String value2) {
            addCriterion("SEND_OBJ_TYPE between", value1, value2, "sendObjType");
            return (Criteria) this;
        }

        public Criteria andSendObjTypeNotBetween(String value1, String value2) {
            addCriterion("SEND_OBJ_TYPE not between", value1, value2, "sendObjType");
            return (Criteria) this;
        }

        public Criteria andSendStatusIsNull() {
            addCriterion("SEND_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSendStatusIsNotNull() {
            addCriterion("SEND_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSendStatusEqualTo(String value) {
            addCriterion("SEND_STATUS =", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusNotEqualTo(String value) {
            addCriterion("SEND_STATUS <>", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusGreaterThan(String value) {
            addCriterion("SEND_STATUS >", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusGreaterThanOrEqualTo(String value) {
            addCriterion("SEND_STATUS >=", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusLessThan(String value) {
            addCriterion("SEND_STATUS <", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusLessThanOrEqualTo(String value) {
            addCriterion("SEND_STATUS <=", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusLike(String value) {
            addCriterion("SEND_STATUS like", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusNotLike(String value) {
            addCriterion("SEND_STATUS not like", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusIn(List<String> values) {
            addCriterion("SEND_STATUS in", values, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusNotIn(List<String> values) {
            addCriterion("SEND_STATUS not in", values, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusBetween(String value1, String value2) {
            addCriterion("SEND_STATUS between", value1, value2, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusNotBetween(String value1, String value2) {
            addCriterion("SEND_STATUS not between", value1, value2, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNull() {
            addCriterion("SEND_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNotNull() {
            addCriterion("SEND_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSendTimeEqualTo(Date value) {
            addCriterion("SEND_TIME =", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotEqualTo(Date value) {
            addCriterion("SEND_TIME <>", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThan(Date value) {
            addCriterion("SEND_TIME >", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SEND_TIME >=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThan(Date value) {
            addCriterion("SEND_TIME <", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThanOrEqualTo(Date value) {
            addCriterion("SEND_TIME <=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeIn(List<Date> values) {
            addCriterion("SEND_TIME in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotIn(List<Date> values) {
            addCriterion("SEND_TIME not in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeBetween(Date value1, Date value2) {
            addCriterion("SEND_TIME between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotBetween(Date value1, Date value2) {
            addCriterion("SEND_TIME not between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendMobileIsNull() {
            addCriterion("SEND_MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andSendMobileIsNotNull() {
            addCriterion("SEND_MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andSendMobileEqualTo(String value) {
            addCriterion("SEND_MOBILE =", value, "sendMobile");
            return (Criteria) this;
        }

        public Criteria andSendMobileNotEqualTo(String value) {
            addCriterion("SEND_MOBILE <>", value, "sendMobile");
            return (Criteria) this;
        }

        public Criteria andSendMobileGreaterThan(String value) {
            addCriterion("SEND_MOBILE >", value, "sendMobile");
            return (Criteria) this;
        }

        public Criteria andSendMobileGreaterThanOrEqualTo(String value) {
            addCriterion("SEND_MOBILE >=", value, "sendMobile");
            return (Criteria) this;
        }

        public Criteria andSendMobileLessThan(String value) {
            addCriterion("SEND_MOBILE <", value, "sendMobile");
            return (Criteria) this;
        }

        public Criteria andSendMobileLessThanOrEqualTo(String value) {
            addCriterion("SEND_MOBILE <=", value, "sendMobile");
            return (Criteria) this;
        }

        public Criteria andSendMobileLike(String value) {
            addCriterion("SEND_MOBILE like", value, "sendMobile");
            return (Criteria) this;
        }

        public Criteria andSendMobileNotLike(String value) {
            addCriterion("SEND_MOBILE not like", value, "sendMobile");
            return (Criteria) this;
        }

        public Criteria andSendMobileIn(List<String> values) {
            addCriterion("SEND_MOBILE in", values, "sendMobile");
            return (Criteria) this;
        }

        public Criteria andSendMobileNotIn(List<String> values) {
            addCriterion("SEND_MOBILE not in", values, "sendMobile");
            return (Criteria) this;
        }

        public Criteria andSendMobileBetween(String value1, String value2) {
            addCriterion("SEND_MOBILE between", value1, value2, "sendMobile");
            return (Criteria) this;
        }

        public Criteria andSendMobileNotBetween(String value1, String value2) {
            addCriterion("SEND_MOBILE not between", value1, value2, "sendMobile");
            return (Criteria) this;
        }

        public Criteria andSendContentIsNull() {
            addCriterion("SEND_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andSendContentIsNotNull() {
            addCriterion("SEND_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andSendContentEqualTo(String value) {
            addCriterion("SEND_CONTENT =", value, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentNotEqualTo(String value) {
            addCriterion("SEND_CONTENT <>", value, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentGreaterThan(String value) {
            addCriterion("SEND_CONTENT >", value, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentGreaterThanOrEqualTo(String value) {
            addCriterion("SEND_CONTENT >=", value, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentLessThan(String value) {
            addCriterion("SEND_CONTENT <", value, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentLessThanOrEqualTo(String value) {
            addCriterion("SEND_CONTENT <=", value, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentLike(String value) {
            addCriterion("SEND_CONTENT like", value, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentNotLike(String value) {
            addCriterion("SEND_CONTENT not like", value, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentIn(List<String> values) {
            addCriterion("SEND_CONTENT in", values, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentNotIn(List<String> values) {
            addCriterion("SEND_CONTENT not in", values, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentBetween(String value1, String value2) {
            addCriterion("SEND_CONTENT between", value1, value2, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentNotBetween(String value1, String value2) {
            addCriterion("SEND_CONTENT not between", value1, value2, "sendContent");
            return (Criteria) this;
        }

        public Criteria andRcStateIsNull() {
            addCriterion("RC_STATE is null");
            return (Criteria) this;
        }

        public Criteria andRcStateIsNotNull() {
            addCriterion("RC_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andRcStateEqualTo(String value) {
            addCriterion("RC_STATE =", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateNotEqualTo(String value) {
            addCriterion("RC_STATE <>", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateGreaterThan(String value) {
            addCriterion("RC_STATE >", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateGreaterThanOrEqualTo(String value) {
            addCriterion("RC_STATE >=", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateLessThan(String value) {
            addCriterion("RC_STATE <", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateLessThanOrEqualTo(String value) {
            addCriterion("RC_STATE <=", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateLike(String value) {
            addCriterion("RC_STATE like", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateNotLike(String value) {
            addCriterion("RC_STATE not like", value, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateIn(List<String> values) {
            addCriterion("RC_STATE in", values, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateNotIn(List<String> values) {
            addCriterion("RC_STATE not in", values, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateBetween(String value1, String value2) {
            addCriterion("RC_STATE between", value1, value2, "rcState");
            return (Criteria) this;
        }

        public Criteria andRcStateNotBetween(String value1, String value2) {
            addCriterion("RC_STATE not between", value1, value2, "rcState");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("MODIFY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("MODIFY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("MODIFY_DATE =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("MODIFY_DATE <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("MODIFY_DATE >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("MODIFY_DATE <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("MODIFY_DATE in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("MODIFY_DATE not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andOperComIdIsNull() {
            addCriterion("OPER_COM_ID is null");
            return (Criteria) this;
        }

        public Criteria andOperComIdIsNotNull() {
            addCriterion("OPER_COM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOperComIdEqualTo(Long value) {
            addCriterion("OPER_COM_ID =", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdNotEqualTo(Long value) {
            addCriterion("OPER_COM_ID <>", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdGreaterThan(Long value) {
            addCriterion("OPER_COM_ID >", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdGreaterThanOrEqualTo(Long value) {
            addCriterion("OPER_COM_ID >=", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdLessThan(Long value) {
            addCriterion("OPER_COM_ID <", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdLessThanOrEqualTo(Long value) {
            addCriterion("OPER_COM_ID <=", value, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdIn(List<Long> values) {
            addCriterion("OPER_COM_ID in", values, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdNotIn(List<Long> values) {
            addCriterion("OPER_COM_ID not in", values, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdBetween(Long value1, Long value2) {
            addCriterion("OPER_COM_ID between", value1, value2, "operComId");
            return (Criteria) this;
        }

        public Criteria andOperComIdNotBetween(Long value1, Long value2) {
            addCriterion("OPER_COM_ID not between", value1, value2, "operComId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("CREATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("CREATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Long value) {
            addCriterion("CREATE_USER_ID =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Long value) {
            addCriterion("CREATE_USER_ID <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Long value) {
            addCriterion("CREATE_USER_ID >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATE_USER_ID >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Long value) {
            addCriterion("CREATE_USER_ID <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("CREATE_USER_ID <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Long> values) {
            addCriterion("CREATE_USER_ID in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Long> values) {
            addCriterion("CREATE_USER_ID not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Long value1, Long value2) {
            addCriterion("CREATE_USER_ID between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("CREATE_USER_ID not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNull() {
            addCriterion("MODIFY_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNotNull() {
            addCriterion("MODIFY_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdEqualTo(Long value) {
            addCriterion("MODIFY_USER_ID =", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotEqualTo(Long value) {
            addCriterion("MODIFY_USER_ID <>", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThan(Long value) {
            addCriterion("MODIFY_USER_ID >", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("MODIFY_USER_ID >=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThan(Long value) {
            addCriterion("MODIFY_USER_ID <", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThanOrEqualTo(Long value) {
            addCriterion("MODIFY_USER_ID <=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIn(List<Long> values) {
            addCriterion("MODIFY_USER_ID in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotIn(List<Long> values) {
            addCriterion("MODIFY_USER_ID not in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdBetween(Long value1, Long value2) {
            addCriterion("MODIFY_USER_ID between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotBetween(Long value1, Long value2) {
            addCriterion("MODIFY_USER_ID not between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 16 15:12:23 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_sms_info
     *
     * @mbggenerated Mon Nov 16 15:12:23 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}